// ch08 內容：族群差異與台灣。
// 事實依據：research/population-frequencies.verified.json、research/pgst-taiwan.verified.json
// 撰寫原則：等位基因頻率 / 攜帶者比例 / 表現型頻率不混用；台灣醫院世代不等於全台隨機抽樣；東亞平均不等於台灣；缺資料就寫「本次未找到」。
export default {
  id: 'ch08',
  no: 8,
  level: 4,
  title: '族群差異與台灣',
  subtitle: '同一個等位基因，在世界各地的頻率可以差到數十倍：為什麼「東亞平均」不等於「台灣」，又為什麼不能用種族代替基因型',
  minutes: 11,
  stage: {
    aria: '互動 3D 場景「基因地球」：可旋轉的點陣地球，用立柱高度表示某個等位基因（或預測表現型）在各地區的頻率，金色光圈標出台灣，缺資料的地區畫成空心圈；另可切換到遺傳漂變的示意模擬。',
    caption: '拖曳旋轉地球 · 點擊或懸停柱子看數值、來源與限制 · 用下方控制項換基因、換「等位基因/預測表現型」、標出台灣；柱高與遺傳漂變模擬中的數字，前者為文獻數據，後者為「示意」',
  },
  blocks: [
    {
      type: 'p',
      step: 0,
      text: '前面幾章談的是「一個人」的基因型；這一章把鏡頭拉遠，問一個群體的問題：**同一個等位基因，在世界各地有多常見？** 場景裡的基因地球，柱子越高、顏色越偏洋紅，代表這個變異在該地區越常見。你很快會發現兩件事：頻率可以差到數十倍；而且不存在「亞洲高、歐洲低」這麼簡單的規則。族群藥物基因體學的回顧（如 Zhou & Lauschke 2022）指出，這些差異大到讓檢測與用藥策略不能假設所有族群都一樣。',
    },
    { type: 'h3', step: 0, text: '先分清楚三種「頻率」' },
    {
      type: 'p',
      step: 0,
      text: '讀這類圖之前，最重要的是分清楚下表三個不同的數字。把它們混用，是最常見的誤讀。',
    },
    {
      type: 'table',
      step: 0,
      caption: '三種頻率（以臺大醫院（NTUH）全外顯子世代 n=3,562 為例）',
      head: ['名稱', '意思', '舉例'],
      rows: [
        ['{{allele-frequency|等位基因頻率}}', '所有染色體中，某個等位基因占的比例', '`HLA-B*15:02`:4.4%'],
        ['{{carrier frequency|攜帶者比例}}', '至少帶一個該等位基因的人占的比例', '`HLA-B*15:02`:8.8%（312 人）'],
        ['{{phenotype-frequency|表現型頻率}}', '被「預測」為某種代謝者類型的人占的比例', 'CYP2C19 不良代謝者：13.9%'],
      ],
      note: 'NTUH 是因疑似遺傳疾病接受檢測的{{hospital-cohort|醫院世代}}，不是隨機抽樣的一般民眾。表現型頻率多由基因型推估，並非實測酵素活性。',
    },
    {
      type: 'p',
      step: 0,
      text: '場景裡的地區，是 {{cpic|CPIC}} 與 PharmGKB/ClinPGx 使用的{{biogeographic-group|生物地理族群}}（共 9 類，例如東亞、歐洲；場景只畫其中 8 類，美洲原住民組未呈現，拉丁裔是混合族群）。依 Huddart 等人 2019 年的說明，這是對人類多樣性的粗略簡化，只為了讓不同研究能用同一種語言比較；所以「東亞」是許多地區合併的類別，不是台灣，也不是任何單一國家。這些數字多是{{weighted-average|加權平均}}，來自文獻中的小型、非隨機取樣研究，請當成「概略趨勢」，不要當成精確值。',
    },
    { type: 'h3', step: 1, text: 'CYP2C19*3：東亞特別重要的變異' },
    {
      type: 'p',
      step: 1,
      text: '先看 `CYP2C19*3`（無功能等位基因）。依 CPIC 頻率表，它在東亞是 7.25%，歐洲只有 0.16%，約差 45 倍（倍數為自行換算）；其他地區的數字可以在場景裡點柱子看。在歐洲與非洲，無功能的 CYP2C19 幾乎都是 `*2`，但在東亞，`*3` 約占無功能等位基因的五分之一，所以只檢測 `*2` 的檢驗會漏掉這一塊。大洋洲的 14.6% 來自少數研究（各研究範圍 1.7%–33%），不確定性很大，場景中以半透明柱子表示。',
    },
    {
      type: 'p',
      step: 1,
      text: '台灣呢？CPIC 收錄的一項健康成人研究（Wang 2014,n=1,038）中，`*3` 為 5.8%。把 `*2` 與 `*3` 加起來，台灣的 CYP2C19 無功能等位基因約 37–38%；臺大醫院世代預測約 60.9% 是{{intermediate-metabolizer|中間代謝者}}或{{poor-metabolizer|不良代謝者}}，其中不良代謝者 13.9%。把場景切到「預測表現型頻率」，CPIC 推估的東亞不良代謝者約 13.0%、歐洲約 2.4%。請留意，「13%」是由基因型預測的比例，**不是**「13% 的人服藥一定無效」，實際臨床影響還要看藥物與適應症（見第 6 章）。',
    },
    { type: 'h3', step: 2, text: 'CYP2C19*17：方向剛好相反' },
    {
      type: 'p',
      step: 2,
      text: '換成 `CYP2C19*17`（增加功能等位基因），地圖就翻轉了：依 CPIC 表，歐洲 21.5%、非裔美人/加勒比非裔 20.7%，東亞只有 2.05%；臺大醫院世代的 `*17` 僅 0.6%（同篇文章的歐洲比較值為 21.3%）。反映到預測表現型，{{rapid-metabolizer|快速代謝者}}加{{ultrarapid-metabolizer|超快速代謝者}}在歐洲約 31.8%，東亞只有約 2.6%。所以「亞洲人的變異比較多」並不對：每個變異都有自己的地理分布，有的在東亞高，有的在歐洲高。',
    },
    { type: 'h3', step: 3, text: 'CYP2D6*10：等位基因很常見，不等於不良代謝者多' },
    {
      type: 'p',
      step: 3,
      text: '`CYP2D6*10`（降低功能）在 CPIC 的東亞加權平均高達 42.8%（以 67 項研究、n=19,808 計算），歐洲約 1.6%。但要小心：單一研究的範圍從 8.6% 到 64.1%,CPIC 也提醒 `*10` 常被預設判讀、可能被高估，所以請把它看成「四成上下的範圍」。場景裡台灣是**空心圈**：本次沒有找到可核實的台灣實測值（依 Lu 2022 與 Lin 2026 的說明，大型陣列與外顯子研究因為 {{cyp2d6}} 含{{cnv|拷貝數變異}}，把它排除在外）。我們不把東亞的 42.8% 硬當成台灣的數字；「本次未找到」也不等於「台灣沒有資料」。',
    },
    { type: 'h3', step: 4, text: '同一個基因，換一種看法' },
    {
      type: 'p',
      step: 4,
      text: '把場景切到「預測表現型頻率」，畫面幾乎翻過來：依 CPIC 的{{activity-score|活性分數}}切點自行換算，CYP2D6 不良代謝者（活性分數 0）在歐洲約 6.5%，東亞只有約 0.8%。東亞的特色不是「不良代謝者特別多」。整體{{intermediate-metabolizer|中間代謝者}}（活性分數 0.25–1.0）兩地其實都約 38%，差別在組成：東亞以 `*10` 造成的活性分數 0.25–0.5 為主（約 29.4%，歐洲約 9.5%），歐洲則以活性分數 1.0 為主（約 28.5%）。這是兩個不同的數字回答兩個不同的問題：**等位基因頻率**問「這個變異有多常見」，**表現型頻率**問「有多少人的酵素活性因此改變」。另外，東亞約 6.7%、歐洲約 3.7% 因資料缺漏無法分類，所以這些換算只是推估。',
    },
    { type: 'h3', step: 5, text: 'HLA-B*15:02：「亞洲」不是一個數字' },
    {
      type: 'p',
      step: 5,
      text: '轉到 `HLA-B*15:02`（與 {{carbamazepine|卡巴馬平}}嚴重皮膚反應相關，見第 7 章），地球放大到東亞與東南亞。依 CPIC 頻率表收錄的研究，日本約 0.03%、南韓約 0.33%、台灣漢人約 4.5%，到泰國 8.2%、馬來半島 12.3%、越南京族 13.5%。台灣近期兩項大型研究（{{wes|臺大 WES}} 與中國醫大陣列推算）都是 4.4%;CPIC 收錄的台灣泰雅族（n=106）與布農族（n=101）兩項小型研究皆為 0。所以「亞洲」不是一個數字，連「台灣」內部，漢人與這兩個原住民族群也不同（其他原住民族未涵蓋，不能類推）。歐洲約 0.01%，撒哈拉以南非洲為 0。',
    },
    {
      type: 'bars',
      step: 5,
      title: 'HLA-B*15:02 等位基因頻率（除台灣外，皆為 CPIC 頻率表收錄的單一研究；台灣為 NTUH／CMUH 醫院世代）',
      unit: '%',
      max: 15,
      data: [
        { label: '日本', value: 0.03, color: 0x59c2ff, note: 'n=18,604' },
        { label: '南韓', value: 0.33, color: 0x59c2ff, note: 'n=4,128' },
        { label: '中國北方漢人', value: 2.4, color: 0x59c2ff, note: 'n=618' },
        { label: '台灣（近期兩項大型研究）', value: 4.4, color: 0xffc44d, note: 'NTUH 與 CMUH，醫院世代' },
        { label: '泰國', value: 8.2, color: 0x59c2ff, note: 'n=986' },
        { label: '香港華人', value: 9.4, color: 0x59c2ff, note: 'n=7,595' },
        { label: '西爪哇', value: 12.2, color: 0x59c2ff, note: 'n=236' },
        { label: '馬來半島', value: 12.3, color: 0x59c2ff, note: 'n=951' },
        { label: '越南京族', value: 13.5, color: 0x59c2ff, note: 'n=170，樣本小' },
      ],
      note: '國別數字是 CPIC 表中「單一研究」的挑選值，同一國家其他研究可以不同（例如 CPIC 中泰國、香港的其他研究約 8.4%–10.2%）。台灣泰雅族（n=106）、布農族（n=101）為 0，樣本小，不能推論到其他原住民族。',
    },
    {
      type: 'p',
      step: 5,
      text: '等位基因頻率和攜帶者比例又不同：台灣 4.4% 的等位基因頻率，實測的陽性者約 7.7%–8.8%。美國 FDA 核准的 Tegretol 仿單則用「陽性者比例」表示：香港、泰國、馬來西亞與菲律賓部分地區超過 15%，台灣約 10%，日本與韓國低於 1%；那是概略的攜帶者比例，不是等位基因頻率，也和台灣實測值略有差距。另外要注意，這份仿單的建議是讓「祖源屬於遺傳上風險較高的族群」的病人先做檢測，也就是以祖源決定要不要檢測；CPIC 指引則寫明建議不分地區與族群，看的是基因型（見本章後面的說明）。',
    },
    {
      type: 'callout',
      kind: 'taiwan',
      step: 5,
      title: '頻率高的地方，篩檢的效益更大',
      text: '這是「優先順序」的考量：CPIC 對 `HLA-B*15:02` 的建議不分地區與族群，只要知道基因型就適用。衛生主管機關自 2007 年 9 月起要求含 carbamazepine 的藥品仿單加刊 `HLA-B*1502` 檢測建議，2010 年 6 月 1 日起該檢測納入全民健保給付（現行給付條件請以健保署最新規定為準）。2011 年《新英格蘭醫學期刊》的台灣前瞻研究（23 家醫院、4,877 人）中，7.7% 陽性者被建議避開該藥，陰性且服藥者無人發生 SJS/TEN，而依歷史發生率 0.23% 預期約有 10 例。這是與「歷史預期」比較的單組研究，不是隨機對照試驗；詳細機制與證據見第 7 章。',
    },
    { type: 'h3', step: 6, text: 'HLA-B*58:01：「東亞平均」不等於台灣' },
    {
      type: 'p',
      step: 6,
      text: '再看 `HLA-B*58:01`（與別嘌呤醇 allopurinol 的嚴重皮膚反應相關）。CPIC 頻率表的東亞平均是 6.0%，歐洲 0.77%；台灣各項研究約 9%–11.4%（CPIC 收錄的台灣研究最低約 8.8%），臺大醫院世代等位基因頻率 11.0%，約每 5 位就有 1 位是攜帶者（21.1%，醫院世代）。{{twb|台灣人體生物資料庫}}（n=59,448）以 HLA 推估的攜帶者比例約 20.9%，方向一致。{{g6pd}}則要特別小心：臺大世代以基因型推估的缺乏比例約 2.0%（男性 3.64%、女性 0.23%；G6PD 位在 X 染色體，且該研究未計入表現多變的異型合子女性），而該文作者所用的東亞參考值是 0.2%。這兩個數字的定義與樣本不同，不能直接相比；同一篇文章也指出，台灣常見的 Canton 與 Kaiping 型在東亞族群中同樣常見，所以 0.2% 比較像參考資料庫的限制，不宜當成東亞實測盛行率。就 HLA-B*58:01 而言，這些對照的意思是：**東亞平均不能代替台灣實測值**，這正是需要本土資料的原因。健保則自 2022 年 6 月 1 日起給付 `HLA-B*58:01` 檢測（須符合指定條件、每人終生限一次）。',
    },
    {
      type: 'table',
      step: 6,
      caption: '台灣、CPIC 東亞與歐洲的對照（節選）',
      head: ['項目', '台灣（來源）', 'CPIC 東亞', 'CPIC 歐洲'],
      rows: [
        ['`CYP2C19*3` 等位基因', '5.8%(Wang 2014)', '7.25%', '0.16%'],
        ['CYP2C19 預測不良代謝者', '13.9%(NTUH)', '13.0%', '2.4%'],
        ['`HLA-B*58:01` 等位基因', '11.0%(NTUH)', '6.0%', '0.77%'],
        ['`VKORC1` -1639A 等位基因', '88.5%(Lee 2009)', '86.6%', '41.3%'],
        ['{{nudt15}} 預測中間代謝者', '18.6%(NTUH)', '19.4%', '1.36%'],
        ['G6PD 缺乏（基因型推估）', '約 2.0%(NTUH；男 3.64%、女 0.23%)', '0.2%（該文作者所用參考值，非實測）', '本章未取得'],
      ],
      note: '各列的基準不同（等位基因頻率或預測表現型比例），請勿跨列比較。台灣欄位多為醫院世代或小型研究，不是全台隨機抽樣；CPIC 為文獻加權平均。VKORC1 頻率不能單獨決定華法林劑量。G6PD 為 X 染色體連鎖，該列兩個數字的定義與樣本不同，只用來說明「參考資料不同，數字就會不同」，不代表台灣的盛行率是東亞的 10 倍。',
    },
    { type: 'h3', step: 7, text: '為什麼會有這些差異？' },
    {
      type: 'p',
      step: 7,
      text: '遺傳學有幾個通用機制：{{genetic-drift|遺傳漂變}}（頻率的隨機波動，小族群特別明顯）、{{founder-effect|創始者效應}}（少數人離開大族群建立新族群）、{{gene-flow|基因流動}}（遷徙與通婚）和{{natural-selection|天擇}}。場景切到「遺傳漂變示意」：16 個族群起點都是 10%；族群小（N=20）時，頻率上下亂跳，很快就消失或固定，族群大（N=5,000）則幾乎不動。請注意，這是**通用的示意模擬**，不代表任何藥物基因的真實歷史。在這種只有隨機抽樣的中性模型裡，起點為 10% 的族群多半最後是「消失」而不是「固定」（固定的機率約等於起始頻率）；模擬也不含選擇、突變與遷移，而真實族群要看有效族群大小，不是總人口數。',
    },
    {
      type: 'p',
      step: 7,
      text: '老實說，對 `CYP2C19*3`、`CYP2D6*10`、`HLA-B*15:02` 這些等位基因，它們「為什麼」在東亞較常見，目前沒有確定的證據，不能說是哪一種機制造成的。只有少數例子有假說：G6PD 缺乏的分布與瘧疾流行高度相關（Luzzatto 等 2020），被認為是異型合子受瘧疾保護而維持的{{balanced-polymorphism|平衡多型性}}；`CYP3A5*3` 的頻率與離赤道的距離有關（Thompson 等 2004），但那只是關於鹽與水分平衡選擇壓力的假說，並非定論。台灣也有本地的例子：Chien 等 2008 分析臺大醫院單一篩檢中心（約占同期全台新生兒 45%）的資料，發現新生兒 G6PD 缺乏症發生率自 2002 年起由 1.94% 降到 1.61%（摘要並未註明 1.61% 對應哪一年）；2000–2005 年間 15%–25% 的新生兒母親是新移入的女性，作者認為這顯示台灣有細微的基因流動；不過摘要並未量化移民的貢獻，不能把它當成全國趨勢，也不能因此斷言因果。',
    },
    { type: 'h3', step: 8, text: '為什麼不能用「種族」代替基因型？' },
    {
      type: 'p',
      step: 8,
      text: '看完地圖，最容易犯的錯是反過來推：「他是某某人，所以他帶有這個等位基因。」至少有三個理由不行。第一，分組很粗：東亞內部、甚至台灣漢人與原住民之間，差異都很大。第二，頻率是族群層級的機率，不是個人的命運：即使某等位基因在某地很常見，個人仍可能沒有；反過來，頻率低的地方也有人帶有。第三，祖源常被自述或外貌掩蓋：CPIC 2017 年指引舉了一個例子，一群被認為是歐洲裔的 SJS/TEN 病人，12 人中有 4 人帶有 `HLA-B*15:02`，後來發現他們帶有一部分東南亞祖源。該指引在用藥建議中也明確寫道，carbamazepine 的 `HLA-B*15:02` 建議不分病人來自哪個地區或族群都成立。',
    },
    {
      type: 'p',
      step: 8,
      text: '美國國家科學院 2023 年的報告，核心建議也是研究者不應把{{race|種族}}當作人類遺傳變異的代理，改用{{genetic-ancestry|遺傳祖源}}等更精確的描述。所以頻率地圖的用途，是幫我們判斷**哪些檢測在某個地方最值得優先做**、以及**該優先蒐集誰的資料**；要決定一個人的處方，看的是他自己的基因型。',
    },
    {
      type: 'callout',
      kind: 'warn',
      step: 8,
      title: '資料的缺口與差距',
      text: 'CPIC 自己指出，研究較少的族群（如大洋洲、中南亞、拉丁裔）估計誤差更大（尤其是 `*1` 的推算），而且同一等位基因在不同資料來源的數字也不一樣：東亞的 `CYP2C19*3`,CPIC 是 7.25%、gnomAD v4.1 是 8.87%、台灣健康成人研究是 5.8%。所以場景在每根柱子都標了來源，缺資料的地方畫成空心圈，而不是猜一個數字。醫院世代（如 NTUH、CMUH）也不能直接當成全台灣的隨機抽樣結果。',
    },
    {
      type: 'callout',
      kind: 'taiwan',
      step: 8,
      title: '台灣正在補上本土資料',
      text: '{{TPMI|台灣精準醫療計畫（TPMI）}}依 2025 年《Nature》論文已招募 565,390 位參與者，使用針對漢人設計的基因型陣列；{{twb|台灣人體生物資料庫}}官網顯示，截至 2026 年 8 月 31 日有 203,147 人參與（「參與」不等於已完成基因定型）。另一項以 486,956 位 TPMI 參與者為對象的分析（Nature Communications 2025）發現 99.9% 的人至少帶有一個 PGx 變異，但這主要是因為 {{vkorc1|VKORC1}} -1639G>A 極為常見；「有變異」不等於「有臨床問題」。兩項研究的參與人數與範圍不同，不可相加或混用。',
    },
    {
      type: 'keypoints',
      title: '這一章的重點',
      items: [
        '**先問是哪一種頻率**：等位基因頻率、攜帶者比例、預測的表現型頻率是三個不同的數字。',
        '**每個變異有自己的地圖**：`CYP2C19*3` 在東亞高、`*17` 在歐洲高；「亞洲人變異比較多」並不成立。',
        '**「東亞」和「亞洲」都不是一個數字**：`HLA-B*15:02` 在日本約 0.03%、台灣約 4.4%、越南約 13.5%。',
        '**東亞平均不等於台灣**：`HLA-B*58:01` 的台灣實測值（約 9%–11.4%）明顯高於 CPIC 東亞平均 6.0%；沒有可核實的台灣實測值時，誠實標示「本次未找到」。',
        '**差異的成因多半未明**：遺傳漂變、創始者效應、基因流動與天擇都是可能機制，但個別藥物基因為何如此，大多沒有定論。',
        '**看基因型，不要看標籤**：頻率用來決定「哪些檢測值得做」，個人處方看個人的基因型。',
      ],
    },
    {
      type: 'deepdive',
      title: '從等位基因頻率換算到攜帶者比例（哈迪-溫伯格）',
      blocks: [
        {
          type: 'p',
          text: '在{{hardy-weinberg|哈迪-溫伯格平衡}}的理想條件下，若某等位基因頻率為 p，兩份染色體都不帶有的機率是 (1 − p)²，所以攜帶者比例約為 1 − (1 − p)²。以臺大世代的 `HLA-B*15:02` 為例：p = 0.044，得到 1 − 0.956² ≈ 8.6%，與實測陽性者 8.8% 相近；`HLA-B*58:01` 的 p = 0.11，約對應 21%，與台灣人體生物資料庫的 20.9% 相近。',
        },
        {
          type: 'p',
          text: '不過這只是「寬鬆的對應」，不是等號：台灣研究的等位基因頻率是 4.2%–6.0%，直接套公式約得 8.2%–11.6%，而各研究另行實測的陽性者是 7.7%–8.8%。CPIC 頻率表中的二倍型與表現型頻率，也是用同樣的哈迪-溫伯格公式由等位基因頻率推估出來的，並非直接量測；所以它不包含近親婚配、族群分層或選擇等現實因素。',
        },
      ],
    },
    {
      type: 'deepdive',
      title: '讀頻率表要注意版本與來源',
      blocks: [
        {
          type: 'p',
          text: 'CPIC 各基因的頻率表更新時間不同：依表內修訂紀錄，CYP2C19 與 NUDT15 表最後修訂為 2022-03-11,CYP2D6 表為 2024-10-17,HLA-B 表為 2020-02-27。版本不同，數字就可能不同：2017 年 CPIC 指引內文寫 HLA-B*15:02 在東亞為 6.9%，而我們取用的線上頻率表（2026 年 9 月 29 日取用）寫的是 4.56%。因此引用頻率時，要註明來源、版本與取用日期。',
        },
        {
          type: 'p',
          text: '另外，{{gnomad}}的「東亞」是以定序資料推定遺傳祖源的群組，沒有獨立的台灣群；CPIC 是文獻加權平均；台灣研究多是醫院世代或小型志願者。三者差距來自樣本組成與方法，不是誰對誰錯。CYP2D6 的表現型分類也隨版本而異：2019 年 CPIC 與 DPWG 專家共識（Caudle 等 2020）把 `*10` 的活性值定為 0.25，並將活性分數 1.0 歸為中間代謝者，跨研究比較前要先確認用的是哪一版切點。',
        },
      ],
    },
  ],
  quiz: [
    {
      q: 'CPIC 表寫「CYP2C19*3 在東亞的等位基因頻率是 7.25%」，這句話的意思最接近哪一個？',
      options: [
        '在東亞人的所有 CYP2C19 染色體中，約有 7.25% 是 *3',
        '每 100 位東亞人中，約有 7.25 位至少帶有一個 *3',
        '東亞人當中，約有 7.25% 被預測為 CYP2C19 不良代謝者',
        '東亞人當中，約有 7.25% 服用 clopidogrel 後通常會失敗',
      ],
      answer: 0,
      explain: '等位基因頻率是「所有染色體中的比例」。每人有兩份染色體，所以至少帶一個的攜帶者比例會更大；不良代謝者比例由基因型推估，而臨床結果還取決於藥物與適應症，這三者是不同的數字。',
    },
    {
      q: '場景中台灣的 CYP2D6*10 是「空心圈」，而不是直接畫 CPIC 東亞的 42.8%。為什麼？',
      options: [
        '因為台灣人幾乎不帶有 CYP2D6*10，所以不需要畫出柱子',
        '因為 42.8% 對台灣而言數值過高，畫出來會讓圖面失真',
        '因為 CYP2D6 通常與藥物反應無關，所以不需要畫出柱子',
        '因為本次沒找到可核實的台灣實測值，東亞平均不能直接代替',
      ],
      answer: 3,
      explain: '空心圈代表缺資料：「本次沒找到」不等於台灣沒有這個變異，也不能拿東亞平均直接頂替。例如 HLA-B*58:01，台灣實測約 11.0%，就明顯高於 CPIC 東亞平均 6.0%。',
    },
    {
      q: '關於 HLA-B*15:02 的族群差異，下列哪一句最符合資料？',
      options: [
        '日本、台灣、越南的頻率都大致約 4%，所以「亞洲」可視為一個數字',
        '歐洲的頻率高於東亞與東南亞各國，是全球各地區中頻率最高的一區',
        '日本約 0.03%、台灣約 4.4%、越南約 13.5%，各地差異很大',
        '台灣約 4.4%，代表每 100 位台灣人約有 4.4 位帶有此等位基因',
      ],
      answer: 2,
      explain: '依 CPIC 表所收錄的單一研究，日本、台灣、越南的差距達數百倍，歐洲約 0.01%；CPIC 收錄的台灣泰雅族與布農族兩項小型研究更是 0。另外，4.4% 是等位基因頻率，攜帶者比例（實測陽性者約 7.7%–8.8%）是另一個數字；頻率也只是族群層級的機率，不代表個人。',
    },
    {
      q: '在「遺傳漂變示意」中，把族群從 N=20 換成 N=5,000，你會看到什麼？',
      options: [
        '大族群的頻率隨機起伏大，容易消失或固定；小族群幾乎不動',
        '小族群的頻率隨機起伏大，容易消失或固定；大族群幾乎不動',
        '兩種族群的頻率起伏相近，只是大族群需要較多世代才看得出來',
        '兩種族群的頻率都會朝 50% 收斂，只是大族群的速度較慢',
      ],
      answer: 1,
      explain: '遺傳漂變在小族群影響大：隨機抽樣讓頻率大幅起伏，甚至消失或固定；大族群的抽樣誤差小，頻率幾乎不動。這是只含隨機抽樣的通用示意模擬，起點 10% 的族群多半是消失而不是固定，也不代表任何藥物基因的真實歷史。',
    },
    {
      q: '關於 HLA-B*58:01，本章的比較最能說明下列哪一個結論？',
      options: [
        '台灣約 9%–11.4%，高於東亞平均 6.0%，所以東亞平均不能代替台灣',
        '台灣約 9%–11.4%，與東亞平均 6.0% 相近，所以可直接沿用東亞平均',
        '台灣的數字來自全台隨機抽樣，所以比東亞平均 6.0% 更精確可靠',
        '台灣的頻率遠高於歐洲的 0.77%，所以可由族群標籤判斷每個人是否帶有',
      ],
      answer: 0,
      explain: '台灣的數字來自各項研究（包含臺大醫院、中國醫藥大學附設醫院等醫院世代），不是全台隨機抽樣；但方向一致地高於 CPIC 東亞加權平均 6.0%（歐洲 0.77%），所以需要台灣本土資料。頻率是族群層級的機率，個人是否帶有要看基因型；另外，等位基因頻率（約 11%）與攜帶者比例（NTUH 世代約 21%）是兩個不同的數字，不能混用。',
    },
    {
      q: '為什麼 CPIC 指引強調 HLA-B*15:02 的建議「不分病人來自哪個地區或族群」都成立？',
      options: [
        '因為 HLA-B*15:02 在所有族群的頻率都相近，所以不需要區分族群',
        '因為只有亞洲族群才會使用 carbamazepine，所以不需要區分族群',
        '因為基因檢測的結果通常不會有任何誤差，所以不需要區分族群',
        '因為自述族裔或外貌可能掩蓋祖源，所以應直接看個人的基因型',
      ],
      answer: 3,
      explain: '例如被認為是歐洲裔的 SJS/TEN 病人，12 人中有 4 人帶有 HLA-B*15:02，後來發現他們有部分東南亞祖源。頻率地圖只能告訴我們哪裡的檢測更值得優先做；決定個人處方要看個人的基因型。美國國家科學院 2023 年報告也建議，研究者不要把種族當作人類遺傳變異的代理。',
    },
  ],
  sources: [
    { name: 'CPIC CYP2C19 頻率表（表格最後修訂 2022-03-11）', url: 'https://files.cpicpgx.org/data/report/current/frequency/CYP2C19_frequency_table.xlsx', note: 'CYP2C19*2/*3/*17 等位基因與預測表現型頻率；Methods 分頁說明加權平均與哈迪-溫伯格推估' },
    { name: 'CPIC CYP2D6 頻率表（表格最後修訂 2024-10-17）', url: 'https://files.cpicpgx.org/data/report/current/frequency/CYP2D6_frequency_table.xlsx', note: 'CYP2D6*10 等位基因頻率；活性分數換算為本站自行加總' },
    { name: 'CPIC HLA-B 頻率表（表格最後修訂 2020-02-27）', url: 'https://files.cpicpgx.org/data/report/current/frequency/HLA-B_frequency_table.xlsx', note: 'HLA-B*15:02 與 HLA-B*58:01;References 分頁的各國單一研究' },
    { name: 'CPIC VKORC1 頻率表', url: 'https://files.cpicpgx.org/data/report/current/frequency/VKORC1_frequency_table.xlsx', note: 'VKORC1 -1639G>A 與 Lee 2009 台灣漢人研究' },
    { name: 'CPIC NUDT15 頻率表（表格最後修訂 2022-03-11）', url: 'https://files.cpicpgx.org/data/report/current/frequency/NUDT15_frequency_table.xlsx', note: 'NUDT15 預測表現型頻率' },
    { name: 'Lin HH 等。 Pharmacogenomic calling from whole-exome sequencing in the Taiwanese population. Mol Genet Genomic Med 2026', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12819042/', note: '臺大醫院全外顯子世代（n=3,562，醫院世代）；台灣 CYP2C19、NUDT15、HLA-B、G6PD 等數字' },
    { name: 'Lu HF 等。 Comprehensive characterization of pharmacogenes in a Taiwanese Han population. Front Genet 2022', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9452738/', note: '中國醫藥大學附設醫院陣列（n=172,854，醫院世代）' },
    { name: 'Zhou Y, Lauschke VM. Population pharmacogenomics: an update on ethnogeographic differences. Hum Genet 2022', url: 'https://pubmed.ncbi.nlm.nih.gov/34652573/', note: '族群差異回顧' },
    { name: 'Huddart R 等。 Standardized biogeographic grouping system for annotating populations in pharmacogenetic research. Clin Pharmacol Ther 2019', url: 'https://pubmed.ncbi.nlm.nih.gov/30506572/', note: 'CPIC/PharmGKB 的 9 個生物地理族群' },
    { name: 'DailyMed:TEGRETOL (carbamazepine) prescribing information', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8d409411-aa9f-4f3a-a52c-fbcb0c3ec053', note: '仿單中各地區 HLA-B*1502 陽性者比例（2026-09-29 取用，不同版本數字可能微調）' },
    { name: '衛生福利部：含 Carbamazepine 成分藥品的臨床效益仍高於風險，高危險族群宜進行 HLA-B*1502 基因檢測（建檔 99-05-20）', url: 'https://www.mohw.gov.tw/cp-3161-26506-1.html', note: '2007 年 9 月仿單加刊建議；2010 年 6 月 1 日納入健保給付' },
    { name: 'Chen P 等。 Carbamazepine-induced toxic effects and HLA-B*1502 screening in Taiwan. N Engl J Med 2011', url: 'https://pubmed.ncbi.nlm.nih.gov/21428768/', note: '4,877 人前瞻研究（以歷史發生率為對照）' },
    { name: '行政院公報：全民健康保險醫療服務給付項目及支付標準部分診療項目修正總說明（111 年第 2 次）', url: 'https://gazette.nat.gov.tw/EG_FileManager/eguploadpub/eg028093/ch08/type1/gov70/num29/images/AA.pdf', note: 'HLA-B*58:01 檢測（12213B）自 2022 年 6 月 1 日起給付及其條件' },
    { name: 'Caudle KE 等。 Standardizing CYP2D6 genotype to phenotype translation: consensus recommendations from CPIC and DPWG. Clin Transl Sci 2020', url: 'https://pubmed.ncbi.nlm.nih.gov/31647186/', note: '活性分數 0.25 的 *10、活性分數 1.0 歸為中間代謝者（PMID 31647186）' },
    { name: 'Wang TH 等 2014（CPIC CYP2C19 頻率表收錄的台灣健康成人研究）', url: 'https://pubmed.ncbi.nlm.nih.gov/24357089/', note: 'CYP2C19*3 台灣 5.8%(n=1,038;CPIC 頻率表收錄；PMID 24357089)' },
    { name: 'Lee MTM 等 2009（CPIC VKORC1 頻率表收錄的台灣漢人研究）', url: 'https://pubmed.ncbi.nlm.nih.gov/19842934/', note: 'VKORC1 -1639A 台灣漢人 88.5%(n=307;CPIC VKORC1 頻率表收錄；PMID 19842934)' },
    { name: 'Chou WH 等。 Biomarker Research 2024（台灣人體生物資料庫 HLA 推估）', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11067262/', note: 'HLA-B*58:01 攜帶者 20.9%、HLA-B*15:02 攜帶者 8.38%（推估值）' },
    { name: 'Chien YH 等。 Changes in incidence and sex ratio of G6PD deficiency by population drift in Taiwan. Southeast Asian J Trop Med Public Health 2008', url: 'https://pubmed.ncbi.nlm.nih.gov/18567456/', note: '台灣新生兒 G6PD 篩檢與基因流動討論（摘要未量化因果）' },
    { name: 'Luzzatto L, Ally M, Notaro R. Glucose-6-phosphate dehydrogenase deficiency. Blood 2020', url: 'https://pubmed.ncbi.nlm.nih.gov/32702756/', note: 'G6PD 缺乏與瘧疾的平衡多型性假說' },
    { name: 'Thompson EE 等。 CYP3A variation and the evolution of salt-sensitivity variants. Am J Hum Genet 2004', url: 'https://pubmed.ncbi.nlm.nih.gov/15492926/', note: 'CYP3A5*3 與離赤道距離（假說）' },
    { name: 'NHGRI Genetics Glossary:Founder Effect', url: 'https://www.genome.gov/genetics-glossary/Founder-Effect', note: '創始者效應與遺傳漂變的定義' },
    { name: 'Phillips EJ 等。 CPIC guideline for HLA genotype and use of carbamazepine and oxcarbazepine: 2017 update', url: 'https://files.cpicpgx.org/data/guideline/publication/carbamazepine/2017/CPIC_HLA_CBZ_OXC.pdf', note: '建議不分地區族群成立；被誤認為歐洲裔的病人例子（CPIC 內容現於 clinpgx.org）' },
    { name: 'National Academies. Using Population Descriptors in Genetics and Genomics Research (2023)', url: 'https://www.nationalacademies.org/read/26902/chapter/2', note: '不要把種族當作人類遺傳變異的代理' },
    { name: 'Yang HC 等。 The Taiwan Precision Medicine Initiative provides a cohort for large-scale studies. Nature 2025', url: 'https://pubmed.ncbi.nlm.nih.gov/41092961/', note: 'TPMI:16 家醫學中心、565,390 人' },
    { name: 'Wei CY 等。 Clinical impact of pharmacogenetic risk variants in a large Chinese cohort. Nat Commun 2025', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12241563/', note: '486,956 位 TPMI 參與者；99.9% 至少帶有一個 PGx 變異（主要為 VKORC1）' },
    { name: '台灣人體生物資料庫（Taiwan Biobank）官網', url: 'https://www.twbiobank.org.tw/', note: '截至 2026-08-31 有 203,147 人參與；數字會定期更新' },
  ],
}
