// ch10 內容：前沿——腫瘤（體細胞）、多基因、AI 與資料
// 事實來源：research/frontiers.verified.json。verified:false 的數字一律以「該研究報告…」等歸屬語氣呈現。
export default {
  id: 'ch10',
  no: 10,
  level: 4,
  title: '前沿：腫瘤、多基因與 AI',
  subtitle: '基因不只是遺傳來的，答案也不只藏在一個基因裡',
  minutes: 13,
  stage: {
    aria: '前沿導覽 3D 場景，含三個主題：腫瘤細胞與 EGFR 標靶藥、示意的 GWAS 曼哈頓景觀，以及 AI 與資料（知識網路、預測對照實驗、族群多樣性、在地生物資料庫）。',
    caption: '用下方「主題」切換三個場景 · 拖曳旋轉 · 點擊或滑過物件看說明 · 所有柱子、散布點、訊號強弱皆為「示意」',
  },
  blocks: [
    // ───────── ① 腫瘤：體細胞 vs 生殖細胞 ─────────
    {
      type: 'h3',
      text: '先分清楚：遺傳來的，還是後來長出來的',
    },
    {
      type: 'p',
      step: 0,
      text: '前面幾章談的基因，幾乎都是**遺傳來的**：CYP2D6、HLA-B 這些變異來自父母，存在你身體幾乎每一個細胞，一輩子不變，這叫{{germline|生殖細胞變異}}。癌症則多了另一種故事：腫瘤細胞在你出生**之後**才累積出新的突變，只存在那一群細胞裡，這叫{{somatic|體細胞突變}}，不會傳給子女，一般也不會出現在你的血球。',
    },
    {
      type: 'p',
      step: 0,
      text: '場景一開始就是這個對比：每個細胞都有藍色菱形（遺傳變異），只有腫瘤細胞群後來多出紅色星星（體細胞突變）。所以癌症用藥，醫師要看的不只是你「繼承了什麼」，還有腫瘤「後來變成了什麼」。（不過並非所有抗癌藥都只看腫瘤：有些抗癌藥的毒性，仍取決於遺傳來的生殖細胞基因型，例如第 7 章談過的 DPYD、UGT1A1、TPMT 與 NUDT15。）',
    },
    {
      type: 'callout',
      kind: 'info',
      title: '少數例外：BRCA1/2 兩種檢測都有',
      text: '「癌症就是體細胞突變」並不是鐵則。BRCA1/2 同時有遺傳（生殖細胞）與腫瘤（體細胞）兩種檢測：FDA 伴隨式診斷清單同時列有以全血檢測的 BRACAnalysis CDx，以及以腫瘤組織檢測的 FoundationOne CDx（皆對應卵巢癌的 olaparib）。血液癌本身就長在血液裡，所以「腫瘤的突變不在血球」是一般情況，不是絕對。另外，只定序腫瘤組織時，光看結果不容易分辨變異是遺傳來的還是腫瘤才有的，有時需要另以血液確認。',
    },
    {
      type: 'p',
      step: 1,
      text: '以肺腺癌為例。{{EGFR|表皮生長因子受體}}嵌在細胞膜上，細胞內側的{{kinase|激酶}}區平常要等生長因子（場景中的粉紅分子）來「敲門」才會短暫啟動。某些腫瘤的 EGFR 帶有**活化突變**，開關卡在「開」，不必敲門就持續把增殖訊號（青色粒子）送往細胞核，這類能推動癌細胞生長的突變稱為{{driver-mutation|驅動突變}}。場景已切到「分子：EGFR 受體」的「活化突變型」：看青色訊號如何不停湧向細胞核。要注意：EGFR 的突變不只一種，各種突變對第一代藥物的反應並不相同（有些對藥物敏感，有些本身就不易有反應），所以「有 EGFR 突變」不等於「第一代藥一定有效」；本站不逐一展開。',
    },
    {
      type: 'p',
      step: 2,
      text: '標靶藥{{TKI|酪胺酸激酶抑制劑}}的策略很直接：占住激酶的 ATP 口袋，ATP 進不來，訊號就中斷。這也是為什麼用藥前要先檢測腫瘤：FDA 把提供「安全且有效使用某項治療所必需資訊」的檢測稱為{{companion-diagnostic|伴隨式診斷}}。HER2 的檢測早在 1997–1998 年就核准；EGFR「突變」的首批伴隨式診斷則遲至 2013 年，距 2004 年發現 EGFR 突變約 9 年。（點場景中的口袋或藥物分子可看說明。）',
    },
    {
      type: 'p',
      step: 3,
      text: '但腫瘤會**演化**。第一代藥物用了一段時間後，部分腫瘤在藥物壓力下出現第二個突變{{T790M}}（腫瘤內的細胞本來就不完全一樣，這類抗藥細胞可能原本就以少數形式存在，也可能後來才出現；用藥後它們被篩選出來、逐漸成為主力），位在 ATP 口袋旁的「守門員」位置（場景中的紅球，為示意）。它讓激酶與 ATP 結合得更緊，第一代這類與 ATP 競爭的藥物效力大減，訊號恢復。一項針對 155 名產生抗藥性並再次切片的病人的研究，報告其中 63% 出現 T790M（文獻數字，不是場景比例）。針對它設計的藥物（如 osimertinib）則能同時抑制敏感突變與 T790M。這就是{{acquired-resistance|後天抗藥性}}：腫瘤基因檢測不一定「一次就好」。',
    },
    {
      type: 'p',
      step: 4,
      text: '如果腫瘤根本沒有這個突變呢？場景切成「野生型」再加藥：藥物照樣占住口袋，但腫瘤原本就不靠 EGFR 增殖，幾乎沒效果（示意）。真實的 IPASS 試驗（東亞不吸菸或曾輕度吸菸的晚期肺腺癌，共 1,217 人）正是如此：gefitinib 相對於化療的「惡化或死亡風險比」（比較的是無惡化存活期，不是總存活期），在 EGFR 突變陽性者（261 人）為 **0.48**，在突變陰性者（176 人）卻是 **2.85**；這是依突變狀態分組的分析，1,217 人中只有這 437 人有可評估的突變結果。同一顆藥，對有突變者遠優於化療，對沒有突變者反而較差；整體的 0.74 是被突變陽性者拉出來的。IPASS 當初是依臨床特徵收案，並不是依突變篩選，這也是後來的試驗改為{{trial-enrichment|依生物標記篩選受試者}}的經典理由。',
    },
    {
      type: 'facts',
      items: [
        { value: '55.7%', label: '台灣多中心前瞻性研究的 EGFR 突變率', note: '1,772 名未曾治療的肺腺癌病人（2011–2013）。是該族群的研究比例，不是全民比例，更不是個人機率。' },
        { value: '51.4%', label: 'PIONEER：7 個亞洲地區的晚期肺腺癌', note: '1,450 人；印度僅 22.2%，其餘地區 47.2–64.2%。研究由藥廠贊助。' },
        { value: '47%', label: '亞太地區的系統性回顧平均', note: '全球回顧共 151 項研究、33,162 人；其中亞太地區 87 項研究、12,819 人，平均 47%，各研究範圍 20–76%。平均值不是個人機率。' },
      ],
    },
    {
      type: 'callout',
      kind: 'taiwan',
      title: '台灣特別在意肺腺癌的基因檢測',
      text: '上面三個數字都來自肺腺癌病人的研究（前兩項是晚期或未曾治療的病人，第三項是多項研究的區域平均），遠高於文獻中常被引用的西方約 10–20%（該數字本站未逐一查證來源）。一項涵蓋 11,678 名病人的全國資料庫研究還報告，女性病人 91.8%、男性 33.3% 從不吸菸，且抽菸越多、開始越早，EGFR 突變率越低。所以台灣的肺腺癌基因檢測特別有意義。但請記得：EGFR 突變是腫瘤的體細胞突變，不會遺傳；各研究數字差異很大，也不能拿來當作你個人的機率。',
    },
    // ───────── ② 多基因 ─────────
    {
      type: 'h3',
      text: '多數藥物反應不是「一個基因說了算」',
    },
    {
      type: 'p',
      step: 5,
      text: '前面章節的例子（CYP2C19、HLA-B*15:02）常有「一個基因、一個明確結果」的漂亮故事，但多數藥物反應不是這樣。CPIC 2017 年華法林指引寫明：CYP2C9、VKORC1、CYP4F2 與 CYP2C 基因叢集的常見變異，**加上**已知的非遺傳因素（年齡、體重、併用藥物…），合計也只能解釋約 **50%** 的劑量變異。在歐洲族群，三個基因最多分別解釋約 18%、30%、11%（這是指引引用的歐洲族群上限，其他族裔較低；CYP4F2 的貢獻較小，場景中它的效應是刻意畫小的示意，並不對應這個 11%）。要找出這些基因，靠的是{{GWAS|全基因體關聯分析}}：掃描全基因體數十萬到數百萬個位點，畫成「曼哈頓圖」，越高越顯著，紅線是全基因體顯著門檻（5×10⁻⁸）。場景已切到「② GWAS 景觀」——注意，**這座山是示意資料，不是真實 GWAS**，山的高度也不等於文獻中的解釋比例。',
    },
    {
      type: 'p',
      text: '華法林的圖像是「少數大效應基因，加上一個小效應基因」。一項 1,053 名瑞典病人的研究報告，調整已知因素後才浮現 CYP4F2（P = 8.3×10⁻¹⁰）；把場景的樣本數往右拉，CYP4F2 才會越過紅線：統計檢定力取決於樣本數與效應大小。',
    },
    {
      type: 'p',
      step: 6,
      text: '大效應變異則完全不同。僅 85 名肌病病例與 90 名對照（皆服用 80 mg simvastatin）的 GWAS，就在 SLCO1B1 找到強訊號（標記位點 P = 4×10⁻⁹）。與其幾乎完全連鎖的 rs4149056，每多一個 C 等位基因，肌病的{{odds-ratio|勝算比}}為 4.5（95% 信賴區間 2.6–7.7）。相反地，史他汀降低 LDL 的反應是多基因性狀，Postmus 等人把多項研究合併的{{meta-analysis|統合分析}}用了最多 18,596 人並以 22,318 人驗證，才找出數個位點。',
    },
    {
      type: 'p',
      step: 7,
      text: '抗憂鬱藥療效更接近另一個極端。一項 2,799 名重度憂鬱症病人的早期分析，用常見變異加總來估計{{heritability|遺傳度}}（稱為 SNP 遺傳度），得到約 42%：意思是療效個體差異中，可歸因於「常見變異加總」的比例，並不是「已經找到的變異解釋了 42%」。但{{standard-error|標準誤}}（估計的不確定度）高達 0.180，粗估的 95% 信賴區間大約從 7% 到 77%，估計非常不精確；後來一項約 5,000 人的更大分析（Pain 等人，2022）估計低得多：緩解約 13%（標準誤 0.056），症狀改善幅度則與 0 沒有顯著差異，而且沒有找到達全基因體顯著的位點。這是{{polygenic|多基因}}的典型：無數效應微小的變異疊加，每個位點的效應小到需要非常大的樣本才看得見，所以即使加總起來有貢獻，也找不到哪個基因說了算（這種落差稱為{{missing-heritability|缺失的遺傳度}}）。把場景樣本拉到最大，也只有寥寥幾個位點越過門檻。',
    },
    {
      type: 'callout',
      kind: 'info',
      title: '高遺傳度不等於一個基因就能預測',
      text: '阿米胥人的研究報告，clopidogrel 的血小板反應{{heritability|遺傳度}}高達 0.73，但單一變異 CYP2C19*2 只解釋約 12%。遺傳度是族群層級的估計，不能說成「CYP2C19*2 能預測 73%」；那個數字也來自特定族群，不宜直接套用到其他族群。把許多微小效應加總成{{PRS|多基因風險分數}}的想法很吸引人，但多篇 2023–2026 年的回顧指出，藥物基因體的 PRS 尚未充分驗證、臨床效益仍待證明，不足以用於常規照護（效應量小、GWAS 偏歐洲族裔、服藥族群樣本小）。',
    },
    {
      type: 'callout',
      kind: 'clinical',
      title: '「多基因面板」不等於「多基因風險分數」',
      text: '同時檢測多個已知藥物基因的**面板**是另一回事（詳見第 9 章）。PREPARE 研究（歐洲 7 國，收案 6,944 人；非盲的叢集隨機交叉實施研究）以 12 個基因、50 個變異導引用藥。全體分析約 6,193 人，臨床上有意義的不良反應為 21.5%，對照組為 28.6%（OR 0.70）；主要（守門）檢定則以有可行動結果的 1,558 人為關鍵子群，為 21.0% 對 27.7%（OR 同為 0.70）。兩組數字來自同一項試驗、不同的分析族群，不要混用。注意 OR 0.70 不等於「風險降低 30%」，絕對差約 7 個百分點；受試者 97.7% 自述為歐洲、地中海或中東族裔，能否類推到台灣需要在地資料。',
    },
    // ───────── ③ AI 與資料 ─────────
    {
      type: 'h3',
      text: 'AI 能幫上什麼忙？先看它吃什麼資料',
    },
    {
      type: 'p',
      step: 8,
      text: '把前面的研究想成一張巨大的網：基因—藥物—反應，每條線背後都是一批論文與指引。AI 常被拿來在這張網上「找還沒連上的線」，場景中的紫色「？」就是示意的候選關聯（例如依相似的藥物、酵素與變異去推測）。但它只能從**資料裡有的東西**學起，每條候選線也都仍需要實驗與臨床資料驗證。點節點可看說明。',
    },
    {
      type: 'p',
      step: 9,
      text: '基因檢測常揪出{{VUS|意義未明變異}}：看到了，卻不知道有沒有功能。做法之一是{{MAVE|多重功能分析}}，一次量測數千個變異；例如 NUDT15 的分析在 3,097 個可能的{{missense|錯義變異}}中測量了 2,922 個的蛋白質豐度（另有細胞毒性實驗），兩者合計找出 1,152 個有害變異。另一條路是 AlphaMissense 這類{{variant-predictor|變異效應預測器}}（Google DeepMind，Science 2023），它把 89% 的錯義變異分為可能良性或可能致病。但它預測的是**通用臨床致病性**，不是某個藥物的代謝功能。',
    },
    {
      type: 'p',
      step: 9,
      text: '2026 年的兩項獨立分析（其中一篇是預印本）報告，在 CYP2C9 等藥物基因上，預測與實驗活性可能脫鉤。其中一篇彙整 CYP2C9、CYP2C19、NUDT15 共 26,198 個錯義變異的實驗資料，發現 CYP2C9 有 28%（4,421 個中的 1,236 個）的變異在「活性」與「豐度」兩種實驗讀值之間不一致；而 195 個「穩定但無活性」的 CYP2C9 變異中，有 38 個被 AlphaMissense 判為可能良性。這些是近期結果，仍待更多獨立驗證。所以 AI 是很好的初篩，不是功能實驗的替代品（場景中紅點=AI 說像良性、實驗卻顯示功能喪失；散布點的相關程度與紅點比例約 8% 都是任意設定，不代表上述 28% 或 38/195 的文獻數字，兩軸的單位也不同，虛線僅供參考）。',
    },
    {
      type: 'p',
      text: 'AI 也不會自動比簡單公式準：一篇系統性回顧（23 項研究，全部高偏誤風險）指出，目前無法判定機器學習與傳統線性公式何者預測華法林劑量較準。',
    },
    {
      type: 'p',
      step: 10,
      text: 'AI 和 GWAS 都吃資料，資料偏一邊，模型就偏一邊。GWAS Diversity Monitor（資料檢查日 2026-09-16，以探索階段參與者計）顯示，累計的探索階段參與者約 88.18% 為歐洲血統，亞洲 6.17%，非洲僅 0.28%。這是所有 GWAS 的統計（本站沒找到專屬藥物基因體研究的比例），且是即時儀表板，數字會隨時間變動；本站也未查證這個累計是否重複計入被多項研究共用的資料庫，所以請當作粗略比例，而不是不重複的人數。Martin 等人（2019）指出，多基因分數在歐洲血統者身上的準確度高出其他族群數倍，這就是{{ancestry-bias|祖先偏誤}}。',
    },
    {
      type: 'p',
      step: 11,
      text: '補足缺口的做法之一是建立在地的大型{{biobank|生物資料庫}}。{{TPMI|台灣精準醫療計畫}}由中央研究院與 16 家醫學中心合作，已招募 565,390 人，使用針對漢人族群最佳化的 {{snp|SNP}} 晶片，並可連結電子病歷（Nature 2025）。一項台灣人體生物資料庫研究以客製化晶片分析 103,106 名漢人，報告約 87.3% 的人帶有已知的功能性藥物反應變異，但「帶有」不等於「需要調整處方」。美國 All of Us 在 2024 年釋出 245,388 人的全基因體序列，UK Biobank 約有 50 萬名參與者、以歐洲血統為主。這些計畫的技術與定義不同（晶片 vs 全基因體），球體體積與各來源所列的人數成正比（台灣人體生物資料庫為單一研究分析的人數，資料庫本身的規模見第 8 章），不宜直接當作品質高低。',
    },
    {
      type: 'callout',
      kind: 'taiwan',
      title: '台灣的檢測與資料基礎',
      text: '依台灣藥物基因體學會（PGST）轉知的食藥署公文：食藥署自 2022 年 7 月 1 日起受理「精準醫療分子檢測實驗室」（簡單說，是可執行「實驗室開發檢測（LDT）」的實驗室）認證申請，2026 年 4 月廢止舊的列冊登錄要點，新版線上認證管理系統自 2026-08-10 起啟用（法源為《特定醫療技術檢查檢驗醫療儀器施行或使用管理辦法》第 37 條第 2 項）。PGST 也出版《健保伴隨式基因檢測抗癌藥物指引》，涵蓋 13 個癌症標靶基因/蛋白。本站未取得食藥署與健保署的原始公告，實際規定與給付條件請以官方公告為準。',
    },
    // ───────── 進階與界線 ─────────
    {
      type: 'deepdive',
      title: 'GWAS 的三個關鍵概念：多重檢定、連鎖不平衡、PRS 的可攜性',
      blocks: [
        {
          type: 'p',
          text: '**為什麼門檻是 5×10⁻⁸？** GWAS 一次檢定數十萬到數百萬個位點，如果沿用一般的 0.05，光靠運氣就會冒出大量假陽性。常見的做法是把 0.05 除以全基因體上大約一百萬個彼此獨立的常見變異檢定，得到約 5×10⁻⁸。所以場景裡的紅線不是隨便畫的，而是「檢定很多次」的代價。',
        },
        {
          type: 'p',
          text: '**為什麼訊號是一座山，而且標記位點不一定是真正的原因？** 相鄰的變異常常一起遺傳，這稱為連鎖不平衡（linkage disequilibrium）。GWAS 挑出的「標記位點」只是與真正造成效應的位點幾乎綁在一起（例如 SLCO1B1 的標記位點與 rs4149056），因此一個真正的訊號會連帶拉高周圍一整片位點，畫成曼哈頓圖上的一座山，而不是一根針。',
        },
        {
          type: 'p',
          text: '**PRS 為什麼不容易跨族群使用？** 多基因風險分數是把許多變異各自的效應大小（來自 GWAS）加權加總。但這些效應大小是在特定族群估出來的；不同族群的連鎖不平衡型態與等位基因頻率不同，效應大小換到另一個族群往往就不準（Martin 等人，2019），加上 GWAS 又偏歐洲血統，這正是前面「祖先偏誤」的後果之一。',
        },
      ],
    },
    {
      type: 'deepdive',
      title: 'CYP2D6：為什麼結構變異這麼難抓？',
      blocks: [
        {
          type: 'p',
          text: 'CYP2D6 旁邊有高度相似的假基因 CYP2D7，兩者常出現 CYP2D6–CYP2D7 融合（hybrid）等位基因，再加上整段基因的缺失或重複，使它成為最難分型的藥物基因之一。{{structural-variant|結構變異}}若被漏掉，由基因型推定的表現型就可能錯。美國一項涵蓋 104,509 個檢體的研究報告，CYP2D6 結構變異見於 13.1% 的人，約 30% 的不良代謝者是因結構變異造成；但這是美國資料，台灣與東亞的分布不同，不能直接套用。{{long-read|長讀長定序}}（如 nanopore Cas9）能解出許多短片段檢測看不到的融合與結構變異。',
        },
        {
          type: 'p',
          text: '另一個不確定來源是{{phenoconversion|表現型轉換}}：併用強效 CYP2D6 抑制劑時，CPIC 參照 Borges 等人的方法把{{activity-score|活性分數}}視為 0，中效抑制劑乘以 0.5，較新指引（2021 鴉片類、2024 β 阻斷劑）只調整強效與中效抑制劑，其中 2024 β 阻斷劑指引明確寫弱效不建議調整。但這只是常用的簡化規則，不是精確定律；2023 年 CPIC SSRI 指引也指出調整方式尚無共識，不是讓人自行計算劑量的工具。',
        },
      ],
    },
    {
      type: 'callout',
      kind: 'warn',
      title: '範圍與界線：哪些還不是常規',
      text: '**基因編輯不等於藥物基因體學**：藥物基因體學是依基因型選藥與調整；依 FDA 新聞稿，2023 年 12 月 8 日核准的第一個 CRISPR/Cas9 療法 Casgevy（用於鐮刀型貧血）則是直接編輯病人自己造血幹細胞的基因體（改的是 BCL11A 的紅血球特異性增強子，以重新啟動胎兒血紅素，並非修正致病突變本身），層次不同，且需要骨髓清除預處理（高劑量化療）。**表觀遺傳與腸道菌**也還不是常規檢測：腫瘤的 MGMT 啟動子甲基化是少數證據較成熟的例外，生殖細胞層次與微生物組導向的用藥多屬機轉與前臨床證據。本章的「示意」畫面不是劑量計算器，也不構成醫療建議。',
    },
    {
      type: 'keypoints',
      items: [
        '生殖細胞變異遺傳自父母、存在每個細胞；體細胞突變出生後才出現、只在腫瘤，不會傳給子女。癌症標靶藥常看後者，並靠伴隨式診斷選藥；但氟嘧啶（DPYD）、irinotecan（UGT1A1）、硫嘌呤（TPMT/NUDT15）等抗癌藥的毒性，仍取決於遺傳來的生殖細胞基因型。',
        '標靶藥占住突變 EGFR 的 ATP 口袋；沒有突變時可能無效（IPASS 的無惡化存活風險比：陽性 0.48、陰性 2.85）。EGFR 突變不只一種；腫瘤會演化出 T790M 等抗藥突變，檢測不一定一次就好。',
        '多數藥物反應是多基因的：華法林的常見基因加非遺傳因素合計只解釋約 50% 的劑量變異。大效應變異（SLCO1B1）小樣本就能發現；微小效應要靠大樣本。',
        '遺傳度高不等於一個基因能預測（clopidogrel：0.73 對 12%）；藥物基因體的 PRS 尚未用於常規照護。',
        'AI（如 AlphaMissense）是初篩工具，預測的是通用致病性，不能取代功能實驗；它取決於資料，而 GWAS 參與者約 88% 為歐洲血統，台灣的 TPMI 等在地資料庫因此重要。',
      ],
    },
    {
      type: 'callout',
      kind: 'info',
      title: '回到小雅、阿明和老周',
      text: '第 1 章的三位主角是虛構的，情境也沒有指定藥物，所以我們無法斷定他們各自「真正」的原因。但走完這十章，你有一組線索可以逐項思考：藥在身體裡的旅程有沒有差別（第 4 章：吸收、分布、代謝、排除）；肝臟酵素代謝得快或慢（第 5–6 章，例如 CYP2C19、CYP2D6），代謝太慢可能讓藥累積、出現不良反應，前驅藥代謝太慢則可能沒有療效；免疫辨識的差異（第 7 章，例如 HLA-B*15:02 與嚴重皮膚反應）；還有基因以外的因素，例如年齡、肝腎功能、併用藥物與服藥習慣（第 1 章）。這些因素常常同時存在，基因往往只是其中一部分，本章的華法林與抗憂鬱藥就是例子。基因檢測是輔助的資訊，不能取代醫師與藥師的判斷，也不是叫任何人自行停藥或換藥。想繼續探索，可以到本站最下方的「資源與延伸閱讀」，那裡整理了 CPIC、ClinPGx 與台灣藥物基因體學會（PGST）等資源；想知道自己適不適合做檢測，請和醫師或藥師討論。',
    },
  ],
  quiz: [
    {
      q: '關於肺腺癌病人腫瘤中的 EGFR 活化突變，下列哪個敘述正確？',
      options: [
        '出生後才在腫瘤細胞出現，不會傳給子女',
        '遺傳自父母，所以子女通常也會帶有它',
        '存在全身每個細胞，所以抽血就能反映',
        '台灣一般民眾約有 55.7% 帶有此突變',
      ],
      answer: 0,
      explain: '這是體細胞突變，只在腫瘤細胞內，不會遺傳。55.7% 是一項台灣研究中「未曾治療的肺腺癌病人」的比例（1,772 人），不是全民比例，也不是個人機率。',
    },
    {
      q: 'IPASS 試驗中，gefitinib 相對於化療的無惡化存活風險比，在 EGFR 突變陽性者為 0.48，在突變陰性者為 2.85。這最能說明什麼？',
      options: [
        '風險比越大代表藥效越好，2.85 勝過 0.48',
        '這顆藥對亞洲人的肺癌通常都優於化療，不必先檢測',
        '突變陰性者通常不需要治療，只要定期追蹤即可',
        '標靶藥效果取決於腫瘤有無對應標記，需依標記篩選',
      ],
      answer: 3,
      explain: '同一顆藥，對有突變者遠優於化療，對沒有突變者反而較差。整體的 0.74 是被突變陽性者拉出來的，所以不能說「對亞洲人比化療好」。另外這些是無惡化存活的風險比，不等於總存活。',
    },
    {
      q: '為什麼 SLCO1B1 與史他汀肌病的關聯，只要 85 名病例、90 名對照就能在 GWAS 找到，抗憂鬱藥療效卻難以找到單一基因？',
      options: [
        '史他汀的研究經費通常較充足，所以能得到較精確的結果',
        '抗憂鬱藥療效通常與基因無關，所以再大的樣本也找不到',
        'SLCO1B1 效應大；抗憂鬱藥效應微小而分散，需要大樣本',
        'GWAS 通常只能用於病例對照設計，無法分析連續型療效',
      ],
      answer: 2,
      explain: '統計檢定力取決於效應大小與樣本數。大效應變異小樣本就看得見；多基因性狀是無數微小效應的疊加。抗憂鬱藥的早期估計（約 42%，標準誤 0.180）很不精確，後來更大的分析估計低得多，但這不代表與基因無關，只是每個位點的效應太小。',
    },
    {
      q: '關於 AlphaMissense 這類變異效應預測器，下列哪個說法最恰當？',
      options: [
        '它已證明能取代功能實驗，通常不必再做活性測定',
        '它預測的是通用致病性，適合初篩，仍需功能實驗確認',
        '它在藥物基因上通常毫無用處，不應拿來做初篩',
        '它能算出每個藥物的劑量，通常不必再參考指引',
      ],
      answer: 1,
      explain: '近期獨立分析指出預測與藥物基因的實驗活性可能脫鉤，但這些結果尚待更多獨立驗證。因此把它視為初篩工具，而不是取代或全盤否定。',
    },
    {
      q: '阿米胥人的研究報告 clopidogrel 的血小板反應遺傳度高達 0.73，但單一變異 CYP2C19*2 只解釋約 12%。這最能說明什麼？',
      options: [
        '遺傳度是族群層級估計，高遺傳度不代表單一基因能預測個人反應',
        '只要檢測 CYP2C19*2，通常就能預測個人 73% 的反應差異',
        'CYP2C19*2 與 clopidogrel 的反應幾乎沒有關係',
        '這個 0.73 通常適用於各族群，可以直接套用到台灣人身上',
      ],
      answer: 0,
      explain: '遺傳度描述的是族群中差異有多少可歸因於基因差異，不是個人有多少比例由某個基因決定；其餘差異可能來自其他基因、非遺傳因素與測量誤差。而且這是特定族群的估計，不宜直接套用到其他族群。',
    },
    {
      q: '一位肺腺癌病人服用第一代 EGFR 標靶藥一段時間後腫瘤又惡化，再次檢測發現 T790M。下列哪個理解最恰當？',
      options: [
        'T790M 是病人出生就有的生殖細胞變異，代表先前檢測通常有誤',
        '這通常代表病人沒有按時服藥，與腫瘤本身的基因變化無關',
        '所有 EGFR 藥物對 T790M 通常都無效，也沒有其他藥可選',
        '腫瘤在藥物壓力下演化出後天抗藥性，所以檢測不一定一次就好',
      ],
      answer: 3,
      explain: 'T790M 是常見的後天抗藥性機轉之一，它讓激酶與 ATP 結合得更緊。針對它設計的藥物（如 osimertinib）能同時抑制敏感突變與 T790M，所以不是「一律無效」。',
    },
  ],
  sources: [
    { name: 'MedlinePlus Genetics：遺傳與後天變異', url: 'https://medlineplus.gov/genetics/understanding/mutationsanddisorders/genemutation/', note: '生殖細胞與體細胞變異的定義' },
    { name: 'FDA 伴隨式診斷清單', url: 'https://www.fda.gov/medical-devices/in-vitro-diagnostics/list-fda-authorized-companion-diagnostic-devices-in-vitro-and-imaging-tools', note: '伴隨式診斷定義與核准日期（內容更新至 2026-09-28）；BRCA1/2 同時有全血與腫瘤組織兩種檢測' },
    { name: 'FDA PMA 資料庫：EGFR 突變首批伴隨式診斷（P120019、P120022）', url: 'https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpma/pma.cfm?id=P120019', note: 'EGFR 突變首批檢測日期在 FDA 清單與 PMA 資料庫略有差異，本站只說 2013 年' },
    { name: 'Lynch et al., NEJM 2004', url: 'https://pubmed.ncbi.nlm.nih.gov/15118073/', note: 'EGFR 突變與 gefitinib 反應（2004 年發現）' },
    { name: 'Paez et al., Science 2004', url: 'https://pubmed.ncbi.nlm.nih.gov/15118125/', note: 'EGFR 突變與 gefitinib 反應（2004 年發現）' },
    { name: 'Hsu et al., PLoS ONE 2015', url: 'https://pubmed.ncbi.nlm.nih.gov/25789627/', note: '台灣 1,772 名肺腺癌病人的 EGFR 突變率 55.7%' },
    { name: 'Shi et al., J Thorac Oncol 2014(PIONEER)', url: 'https://pubmed.ncbi.nlm.nih.gov/24419411/', note: '亞洲晚期肺腺癌 EGFR 突變盛行率；藥廠贊助' },
    { name: 'Midha et al., Am J Cancer Res 2015', url: 'https://pubmed.ncbi.nlm.nih.gov/26609494/', note: '全球 EGFR 突變盛行率系統性回顧（全球 151 項研究、33,162 人；亞太 87 項、12,819 人，平均 47%）' },
    { name: 'Lin et al., Thoracic Cancer 2025', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12287865/', note: '「西方約 10–20%」出自此文討論段落，本站未逐一查證其引用來源' },
    { name: 'Tseng et al., Oncotarget 2017', url: 'https://pubmed.ncbi.nlm.nih.gov/29228697/', note: '台灣肺腺癌吸菸狀態與 EGFR 突變（回溯性）' },
    { name: 'Mok et al., NEJM 2009(IPASS)', url: 'https://pubmed.ncbi.nlm.nih.gov/19692680/', note: 'EGFR 突變狀態決定 gefitinib 優於或劣於化療' },
    { name: 'Yu et al., Clin Cancer Res 2013', url: 'https://pubmed.ncbi.nlm.nih.gov/23470965/', note: 'EGFR-TKI 後天抗藥性機轉，T790M 頻率' },
    { name: 'Yun et al., PNAS 2008', url: 'https://pubmed.ncbi.nlm.nih.gov/18227510/', note: 'T790M 主要透過提高激酶對 ATP 的親和力造成抗藥，而非單純的空間阻擋' },
    { name: 'CPIC 華法林指引 2017', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5546947/', note: '基因加非遺傳因素約解釋 50% 劑量變異；歐洲族群各基因最多約 18%、30%、11%；EU-PACT、COAG、GIFT 證據' },
    { name: 'Takeuchi et al., PLoS Genet 2009', url: 'https://pubmed.ncbi.nlm.nih.gov/19300499/', note: '1,053 名瑞典病人的華法林劑量 GWAS(CYP4F2)' },
    { name: 'SEARCH Collaborative Group, NEJM 2008', url: 'https://pubmed.ncbi.nlm.nih.gov/18650507/', note: 'SLCO1B1 與史他汀肌病的 GWAS' },
    { name: 'Postmus et al., Nat Commun 2014', url: 'https://pubmed.ncbi.nlm.nih.gov/25350695/', note: '史他汀降 LDL 反應的 GWAS 統合分析' },
    { name: 'Tansey et al., Biol Psychiatry 2013', url: 'https://pubmed.ncbi.nlm.nih.gov/23237317/', note: '抗憂鬱藥療效的常見變異貢獻估計（約 42%，標準誤 0.180，早期估計）' },
    { name: 'Pain et al., Biol Psychiatry Glob Open Sci 2022', url: 'https://pubmed.ncbi.nlm.nih.gov/35712048/', note: '更大的抗憂鬱藥反應 GWAS：緩解的 SNP 遺傳度約 0.132（標準誤 0.056）、症狀改善幅度 −0.018（標準誤 0.032）；無達全基因體顯著的位點' },
    { name: 'Shuldiner et al., JAMA 2009', url: 'https://pubmed.ncbi.nlm.nih.gov/19706858/', note: 'clopidogrel 反應遺傳度 0.73 與 CYP2C19*2 約 12%（阿米胥人）' },
    { name: 'Singh et al., Clin Transl Sci 2024', url: 'https://pubmed.ncbi.nlm.nih.gov/39078255/', note: '藥物基因體 PRS 是否準備好臨床使用' },
    { name: 'Simona et al., 2023', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10311496/', note: 'PRS 能解釋的藥物反應變異仍低' },
    { name: 'Mathey et al., Med Genet 2026', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC13340549/', note: '藥物基因體 PRS「尚未充分驗證、不足以用於常規照護」' },
    { name: 'Swen et al., Lancet 2023(PREPARE)', url: 'https://pubmed.ncbi.nlm.nih.gov/36739136/', note: '12 基因面板預先檢測的非盲叢集隨機交叉實施研究；收案 6,944 人、全體分析約 6,193 人；主要（守門）分析為有可行動結果的 1,558 人（21.0% 對 27.7%，OR 0.70）' },
    { name: 'Suiter et al., PNAS 2020', url: 'https://pubmed.ncbi.nlm.nih.gov/32094176/', note: 'NUDT15 變異的多重功能分析（蛋白質豐度與細胞毒性兩種實驗）' },
    { name: 'Cheng et al., Science 2023(AlphaMissense)', url: 'https://pubmed.ncbi.nlm.nih.gov/37733863/', note: 'AlphaMissense 論文摘要' },
    { name: 'Kırboğa, G3 2026', url: 'https://academic.oup.com/g3journal/advance-article/doi/10.1093/g3journal/jkag248/8776100', note: 'CYP2C9/CYP2C19/NUDT15 五組深度突變掃描資料（共 26,198 個錯義變異）與 AlphaMissense 比較（單一團隊）' },
    { name: 'Xu et al., bioRxiv 2026（預印本）', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC13484531/', note: '預測器在 CYP 藥物基因的限制（未經同儕審查）' },
    { name: 'Zhang et al., J Pers Med 2022', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9147332/', note: '機器學習預測華法林劑量的系統性回顧（23 項研究，皆高偏誤風險，無法判定演算法孰優）' },
    { name: 'GWAS Diversity Monitor', url: 'https://www.gwasdiversitymonitor.com/', note: '即時儀表板；本章引用資料檢查日 2026-09-16 的數字' },
    { name: 'Fatumo et al., Nat Med 2022', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7614889/', note: 'GWAS 族群多樣性；UK Biobank 族群組成的描述' },
    { name: 'Martin et al., Nat Genet 2019', url: 'https://pubmed.ncbi.nlm.nih.gov/30926966/', note: '多基因分數的族群準確度差異' },
    { name: 'Taiwan Precision Medicine Initiative, Nature 2025', url: 'https://pubmed.ncbi.nlm.nih.gov/41092961/', note: 'TPMI 世代：565,390 人' },
    { name: 'Wei et al., npj Genom Med 2021(Taiwan Biobank)', url: 'https://pubmed.ncbi.nlm.nih.gov/33574314/', note: '103,106 名漢人的藥物反應變異輪廓（單一研究的分析人數，非資料庫總人數）' },
    { name: 'All of Us Research Program, Nature 2024', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10937371/', note: '245,388 人的全基因體序列' },
    { name: 'Bycroft et al., Nature 2018(UK Biobank)', url: 'https://pubmed.ncbi.nlm.nih.gov/30305743/', note: '約 50 萬人的基因與表現型資源' },
    { name: 'PGST：廢止「精準醫療分子檢測實驗室列冊登錄申請須知」（2026-04-02；內文載明食藥署自 2022-07-01 起受理認證申請）', url: 'https://www.pgst.org.tw/news_detail?id=611', note: '轉知公文，原始公告本站未直接取得；本站引用其中「2022-07-01 起受理認證申請」一句' },
    { name: 'PGST：廢止列冊登錄管理要點（2026-04-21）', url: 'https://www.pgst.org.tw/news_detail?id=634', note: '轉知公文（FDA品字第1151101125號），原始公告本站未直接取得' },
    { name: 'PGST：食藥署精準醫療分子檢測實驗室認證（2026-08-10）', url: 'https://www.pgst.org.tw/news_detail?id=708', note: '轉知公文，原始公告本站未直接取得' },
    { name: 'PGST：健保伴隨式基因檢測抗癌藥物指引', url: 'https://www.pgst.org.tw/events_detail?id=400', note: '涵蓋 13 個癌症標靶基因/蛋白' },
    { name: 'Del Tredici et al., Front Pharmacol 2018', url: 'https://pubmed.ncbi.nlm.nih.gov/29674966/', note: '美國 104,509 個檢體的 CYP2D6 結構變異（非台灣資料）' },
    { name: 'Rubben et al., PLoS Genet 2022', url: 'https://pubmed.ncbi.nlm.nih.gov/36149915/', note: 'Cas9 標靶 nanopore 長讀長定序解 CYP2D6–CYP2D7 融合等位基因' },
    { name: 'Cicali et al., Clin Pharmacol Ther 2021', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8404400/', note: 'CYP2D6 表現型轉換的臨床整合；抑制劑分類與乘數不一致' },
    { name: 'CPIC 鴉片類指引 2021', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8249478/', note: '僅對強效（活性分數視為 0）與中效（乘以 0.5）抑制劑規定調整' },
    { name: 'CPIC β 阻斷劑指引 2024', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11502236/', note: '弱效 CYP2D6 抑制劑不建議調整' },
    { name: 'CPIC SSRI 指引 2023', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10564324/', note: '指出表現型轉換的調整方式尚無共識' },
    { name: 'FDA 新聞稿：首批鐮刀型貧血基因療法核准', url: 'https://www.fda.gov/news-events/press-announcements/fda-approves-first-gene-therapies-treat-patients-sickle-cell-disease', note: 'Casgevy 核准日 2023-12-08' },
    { name: 'Frangoul et al., NEJM 2024', url: 'https://pubmed.ncbi.nlm.nih.gov/38661449/', note: 'Casgevy（exa-cel）編輯 BCL11A 紅血球特異性增強子' },
    { name: 'Hegi et al., NEJM 2005', url: 'https://pubmed.ncbi.nlm.nih.gov/15758010/', note: '腫瘤 MGMT 啟動子甲基化與 temozolomide 療效' },
    { name: 'Ingelman-Sundberg & Gomez, 2010', url: 'https://pubmed.ncbi.nlm.nih.gov/20415549/', note: 'CYP 基因的表觀遺傳調控「才剛開始被認識」' },
    { name: 'Zimmermann et al., Nature 2019', url: 'https://pubmed.ncbi.nlm.nih.gov/31158845/', note: '腸道細菌對口服藥物的修飾（機轉與前臨床證據）' },
    { name: '微生物組導向用藥的 2026 年回顧', url: 'https://pubmed.ncbi.nlm.nih.gov/42101126/', note: '仍把以微生物組導向的用藥策略列為「新興」' },
  ],
}
