// ch02 術語：從 DNA 到蛋白質
export default [
  { key: 'variant', zh: '基因變異', en: 'Genetic variant', level: 1, aliases: ['變異', '突變'], def: 'DNA 序列與參考序列或多數人不同的地方。變異不一定有害：多數位於不影響功能的位置，有沒有影響要看它的位置與機制。' },
  { key: 'dna', zh: 'DNA（去氧核糖核酸）', en: 'Deoxyribonucleic acid', level: 1, aliases: ['DNA', '去氧核糖核酸'], def: '攜帶遺傳資訊的分子，由兩條互補的長鏈纏繞成雙股螺旋，用 A、T、G、C 四種鹼基寫成密碼。' },
  { key: 'base', zh: '鹼基', en: 'Base (nucleotide base)', level: 1, aliases: ['鹼基對', 'base pair', 'A、T、G、C'], def: 'DNA 的「字母」：腺嘌呤（A）、胸腺嘧啶（T）、鳥糞嘌呤（G）、胞嘧啶（C）。兩股之間 A 只配 T、G 只配 C，這一對就叫鹼基對，也是計算序列長度的單位。RNA 用 U 取代 T。' },
  { key: 'genome', zh: '基因體', en: 'Genome', level: 1, def: '一個生物全部的 DNA 序列。人類單套基因體約有 30 至 32 億個鹼基對（通俗說法為 32 億，完整定序的 T2T-CHM13 版本為 30.55 億，依版本與計算方式而異）。' },
  { key: 'gene', zh: '基因', en: 'Gene', level: 1, def: 'DNA 上的一段序列，是遺傳的基本功能單位；許多基因帶有「製造某一種蛋白質」的指令。' },
  { key: 'rna-polymerase', zh: 'RNA 聚合酶', en: 'RNA polymerase', level: 1, def: '負責轉錄的酵素：沿著模板股前進，依配對規則一個字母一個字母地組出 RNA。' },
  { key: 'template-strand', zh: '模板股', en: 'Template strand', level: 1, aliases: ['編碼股', '模板股/編碼股'], def: '轉錄時被拿來當模板的那一股 DNA；新做出的 mRNA 與它互補，所以 mRNA 的字母序列和另一股（編碼股）相同，只是 T 換成 U。' },
  { key: 'transcription', zh: '轉錄', en: 'Transcription', level: 1, def: '以基因的一股 DNA 為模板，製作出一份 RNA 副本（mRNA）的過程，由 RNA 聚合酶負責。' },
  { key: 'mrna', zh: '傳訊 RNA(mRNA)', en: 'Messenger RNA', level: 1, aliases: ['mRNA', 'RNA', '傳訊 RNA', '信使 RNA'], def: '從 DNA 抄下來、可以離開細胞核的基因副本。它用 U 取代 T，是核糖體製造蛋白質時讀取的「施工稿」。' },
  { key: 'start-codon', zh: '起始密碼子', en: 'Start codon', level: 1, aliases: ['AUG'], def: '通常是 AUG（編碼甲硫胺酸），標示「從這裡開始讀」。' },
  { key: 'splicing', zh: '剪接', en: 'Splicing', level: 1, aliases: ['外顯子', '內含子', 'exon', 'intron'], def: '人類等生物的基因由外顯子與內含子交錯組成；RNA 加工時內含子被切除、外顯子被接起來，成為成熟的 mRNA，這個過程就叫剪接。剪接位點出錯，可能讓讀框改變、蛋白質截短或失去功能。' },
  { key: 'nucleus', zh: '細胞核', en: 'Cell nucleus', level: 1, def: '真核細胞中存放 DNA 的構造，外有帶核孔的雙層膜。mRNA 由核孔進出，DNA 本身不離開細胞核。' },
  { key: 'ribosome', zh: '核糖體', en: 'Ribosome', level: 1, def: '由 RNA 與蛋白質組成的分子機器，沿著 mRNA 每次讀一個密碼子，並把胺基酸接成鏈。' },
  { key: 'codon', zh: '密碼子', en: 'Codon', level: 1, def: 'mRNA 上 3 個字母為一組的單位，決定接上哪一種胺基酸或叫核糖體停止。共有 64 種：61 種指定胺基酸，3 種是終止訊號。' },
  { key: 'trna', zh: '轉送 RNA(tRNA)', en: 'Transfer RNA', level: 1, aliases: ['tRNA', '轉送 RNA', '轉運 RNA', '轉移 RNA'], def: '小型的 RNA 分子，一端能認出 mRNA 上的密碼子（靠反密碼子配對），另一端帶著對應的胺基酸，負責把它送到核糖體。' },
  { key: 'amino-acid', zh: '胺基酸', en: 'Amino acid', level: 1, def: '蛋白質的組成單位。人體蛋白質使用 20 種胺基酸，串成長短不一的鏈。' },
  { key: 'stop-codon', zh: '終止密碼子', en: 'Stop codon', level: 1, aliases: ['終止訊號'], def: 'UAA、UAG、UGA 三種密碼子不指定任何胺基酸，而是告訴核糖體「到此為止」，蛋白質鏈就此完成。' },
  { key: 'translation', zh: '轉譯', en: 'Translation', level: 1, aliases: ['翻譯'], def: '核糖體讀取 mRNA，每 3 個字母（一個密碼子）接上一個胺基酸，把胺基酸串成蛋白質的過程，遇到終止密碼子就停止。' },
  { key: 'genetic-code', zh: '遺傳密碼', en: 'Genetic code', level: 1, def: '「哪一個密碼子對應哪一種胺基酸」的對照規則，共 64 條；絕大多數生物共用同一套標準密碼。' },
  { key: 'protein', zh: '蛋白質', en: 'Protein', level: 1, def: '由胺基酸串成並折疊成特定立體形狀的分子。藥物代謝酵素、藥物作用的受體、運送藥物的轉運蛋白，全都是蛋白質。' },
  { key: 'enzyme', zh: '酵素', en: 'Enzyme', level: 1, def: '加速化學反應的蛋白質。肝臟的藥物代謝酵素會把藥物轉變成別的物質；酵素的功能取決於它的立體形狀。' },
  { key: 'receptor', zh: '受體', en: 'Receptor', level: 1, def: '通常位在細胞表面或細胞內的蛋白質，能與特定分子（包括藥物）結合並傳遞訊號，是許多藥物作用的目標。' },
  { key: 'transporter', zh: '轉運蛋白', en: 'Transporter', level: 1, aliases: ['藥物轉運蛋白', '轉運體', 'Drug transporter'], def: '位在細胞膜上、負責把分子（包括藥物）運進或運出細胞的蛋白質，會影響藥物在體內的分布與排除。例如肝細胞上的 OATP1B1 負責把藥物吸進去，P-gp（P-醣蛋白）負責把藥物趕出來。' },
  { key: 'central-dogma', zh: '中心法則', en: 'Central dogma', level: 1, def: '遺傳資訊的主要流向：DNA → RNA → 蛋白質。資訊由核酸流向蛋白質，而不會從蛋白質倒回核酸。' },
  { key: 'synonymous', zh: '同義變異', en: 'Synonymous variant', level: 1, aliases: ['同義突變'], def: '改變了 DNA 的字母，但因為遺傳密碼有「多個密碼子對應同一胺基酸」，胺基酸沒有改變。多數情況下蛋白質不變，但若影響剪接或表現量，仍可能造成功能差異。' },
  { key: 'missense', zh: '錯義變異', en: 'Missense variant', level: 1, aliases: ['錯義突變'], def: '使密碼子改成指定「另一種」胺基酸的變異，蛋白質中有一顆胺基酸被換掉。影響可以從幾乎沒有到完全失去功能。' },
  { key: 'nonsense', zh: '無義變異', en: 'Nonsense variant', level: 1, aliases: ['無義突變', '提早終止'], def: '使原本指定胺基酸的密碼子變成終止密碼子的變異，蛋白質會提早中止、變短，通常失去功能。' },
  { key: 'promoter', zh: '啟動子/調控區', en: 'Promoter / regulatory region', level: 1, aliases: ['調控區', '啟動子'], def: '位於基因上游、控制「要轉錄多少」的 DNA 區段。這裡的變異不改變蛋白質序列，卻能改變蛋白質的產量，例如 CYP2C19*17。' },
  { key: 'frameshift', zh: '移碼變異', en: 'Frameshift variant', level: 1, aliases: ['移碼', '讀框', '讀框位移'], def: '插入或缺失的字母數不是 3 的倍數，使下游所有密碼子的分組（讀框）整個改變，通常產生完全不同且很快終止的蛋白質。' },
]
