// ch03 術語：等位基因、基因型與表現型
export default [
  { key: 'chromosome', zh: '染色體', en: 'Chromosome', level: 1, def: '把很長的 DNA 包裝起來的結構。人類每個體細胞有 23 對染色體，每一對都是一條來自母親、一條來自父親。' },
  { key: 'locus', zh: '基因座', en: 'Locus', level: 2, aliases: ['locus'], def: '基因或某個變異在染色體上的固定位置。同一個基因座上，可以出現不同版本的等位基因。' },
  { key: 'cyp2c19', zh: 'CYP2C19', en: 'CYP2C19', level: 2, def: '肝臟的一種藥物代謝酵素基因，位於 10 號染色體。它會活化氯吡格雷（clopidogrel），也處理部分質子幫浦抑制劑（胃藥）與抗憂鬱藥；常見的功能變異有 *2、*3（無功能）與 *17（功能增加）。' },
  { key: 'homozygous', zh: '同型合子', en: 'Homozygous', level: 2, def: '同一個基因座上的兩個等位基因相同，例如 CYP2C19 的 *1/*1 或 *2/*2。' },
  { key: 'heterozygous', zh: '異型合子', en: 'Heterozygous', level: 2, def: '同一個基因座上的兩個等位基因不同，例如 CYP2C19 的 *1/*2。' },
  { key: 'star-allele', zh: '星號等位基因', en: 'Star (*) allele', level: 2, aliases: ['星號命名', '星號'], def: '藥物基因常用的等位基因命名法，例如 CYP2C19*2。星號只是編號，背後對應一組特定的 DNA 變異（稱為單倍型）。編號與定義由 PharmVar 管理，而且可能被修訂。' },
  { key: 'pharmvar', zh: 'PharmVar', en: 'Pharmacogene Variation Consortium', level: 3, def: '負責整理、編號與命名藥物基因星號等位基因的國際資料庫。星號的定義可能隨新發現而修訂，所以報告應註明資料庫版本。' },
  { key: 'diplotype', zh: '雙倍型', en: 'Diplotype', level: 2, def: '兩條染色體上各自的單倍型組合，例如 CYP2C19 *1/*2。CPIC 的基因型轉表現型查表就是以雙倍型為單位。' },
  { key: 'haplotype', zh: '單倍型', en: 'Haplotype', level: 2, def: '位於同一條染色體上、傾向一起遺傳的一組變異。一個星號等位基因通常就是一種單倍型。' },
  { key: 'gene-dose', zh: '基因劑量', en: 'Gene dose', level: 3, aliases: ['劑量效應'], def: '功能好的等位基因越多、酵素活性越高的加成式關係。多數藥物代謝酵素是這種「像調光旋鈕」的模式，而不是單純的顯性或隱性。' },
  { key: 'recessive', zh: '隱性', en: 'Recessive', level: 2, aliases: ['顯性', '顯隱性'], def: '傳統遺傳學的說法：必須兩個等位基因都帶有某個版本，性狀才會完全表現出來，稱為隱性；一個就能表現的稱為顯性。藥物基因體學裡多數性狀更適合用「劑量」來理解。' },
  { key: 'activity-score', zh: '活性分數', en: 'Activity score (AS)', level: 2, aliases: ['AS', 'activity score'], def: '給每個等位基因一個活性值（例如正常功能 1、功能降低 0.25 或 0.5、無功能 0），把兩個相加得到總分，再對應到代謝者類別。它是簡化模型，不等於直接測得的酵素活性；各版指引的數值與切點會修訂，跨研究比較前要確認版本。' },
  { key: 'cyp2c9', zh: 'CYP2C9', en: 'CYP2C9', level: 2, def: '另一個肝臟藥物代謝酵素基因，會清除效力較強的 S-華法林（warfarin）與多種非類固醇消炎止痛藥。常見的減弱或無功能等位基因有 *2、*3，CPIC 以活性分數描述。' },
  { key: 'punnett', zh: '龐尼特方格', en: 'Punnett square', level: 2, aliases: ['Punnett', '龐尼特方格', '旁氏表'], def: '用表格列出父母各自可能傳下的等位基因，推算子代各種組合的機率。' },
  { key: 'hardy-weinberg', zh: '哈迪-溫伯格平衡', en: 'Hardy-Weinberg equilibrium', level: 2, aliases: ['Hardy-Weinberg', '哈溫平衡'], def: '在理想族群（隨機交配、無選擇、無突變、無遷移、族群夠大）中，若兩種等位基因頻率為 p 與 q，三種基因型的比例是 p²、2pq、q²。實際族群只是接近；CPIC 頻率表用它由等位基因頻率推估表現型比例。' },
  { key: 'allele-frequency', zh: '等位基因頻率', en: 'Allele frequency', level: 2, aliases: ['對偶基因頻率'], def: '在一個族群的所有染色體中，某個等位基因所占的比例。它和「帶有的人有多少」是不同的數字，不可混用。' },
  { key: 'ultrarapid-metabolizer', zh: '超快速代謝者', en: 'Ultrarapid metabolizer (UM)', level: 2, aliases: ['UM'], def: '預測酵素活性明顯高於正常的類別，例如 CYP2C19 中兩個功能增加的等位基因（*17/*17）。藥物可能被過快代謝：需要酵素活化的藥可能作用過強，靠酵素清除的藥則可能濃度不足。' },
  { key: 'rapid-metabolizer', zh: '快速代謝者', en: 'Rapid metabolizer (RM)', level: 2, aliases: ['RM'], def: '預測酵素活性略高於正常的類別。CYP2C19 中，一個正常功能加一個功能增加的等位基因（*1/*17）屬於此類；並非每個基因都有這一類。' },
  { key: 'normal-metabolizer', zh: '正常代謝者', en: 'Normal metabolizer (NM)', level: 2, aliases: ['NM'], def: '預測酵素活性在一般範圍內的類別，例如兩個等位基因都是正常功能。多數藥物依標準劑量即可，但也有例外（如 CYP3A5 與 tacrolimus）。' },
  { key: 'intermediate-metabolizer', zh: '中間代謝者', en: 'Intermediate metabolizer (IM)', level: 2, aliases: ['IM'], def: '預測酵素活性介於正常與不良之間的類別，常帶一個無功能或功能減弱的等位基因。不同藥物的建議差異很大。' },
  { key: 'poor-metabolizer', zh: '不良代謝者', en: 'Poor metabolizer (PM)', level: 2, aliases: ['PM'], def: '預測酵素活性極低或缺乏的類別，常帶兩個無功能等位基因（CYP2C9 則是活性分數合計 0 到 0.5）。需要酵素活化的藥可能沒有效果，靠酵素清除的藥則濃度容易過高。' },
]
