// ch07 術語：HLA 與嚴重藥物過敏
export default [
  { key: 'carbamazepine', zh: '卡巴馬平', en: 'Carbamazepine', level: 3, aliases: ['Tegretol'], def: '常用於癲癇與三叉神經痛的藥物。帶有 HLA-B*15:02 者使用後發生嚴重皮膚過敏（SJS/TEN）的風險升高，是藥物基因體學最有名的案例之一；台灣自 2010 年 6 月起由健保給付用藥前檢測。' },
  { key: 'peptide', zh: '胜肽', en: 'Peptide', level: 2, aliases: ['肽'], def: '由數個到數十個胺基酸連成的短鏈。細胞會把內部蛋白質切成小片段，放在 HLA 的凹槽裡展示；HLA class I 通常展示約 9 個胺基酸長的胜肽。' },
  { key: 'T cell', zh: 'T 細胞', en: 'T cell', level: 2, aliases: ['T細胞', 'T 淋巴球'], def: '免疫系統的巡邏兵。表面的 T 細胞受體（TCR）會檢查每個 HLA 展示的胜肽，認出異物才啟動攻擊。' },
  { key: 'TCR', zh: 'T 細胞受體', en: 'T-cell receptor', level: 3, def: 'T 細胞表面辨識「HLA + 胜肽（或 HLA + 藥物）」複合物的受體。每個 T 細胞只帶一種特異的 TCR，序列決定它能辨識什麼。' },
  { key: 'cytotoxic T cell', zh: '細胞毒性 T 細胞', en: 'Cytotoxic T lymphocyte (CD8+ T cell)', level: 3, aliases: ['CTL', 'CD8 T 細胞'], def: '能辨識 HLA class I 上的抗原，並釋放 perforin、granzyme B、granulysin 等蛋白質殺死目標細胞的 T 細胞。' },
  { key: 'SCAR', zh: '嚴重皮膚不良反應', en: 'Severe cutaneous adverse reactions', level: 3, def: '藥物引起的 T 細胞媒介嚴重皮膚反應的總稱，包括 SJS/TEN、DRESS 與 AGEP 等。' },
  { key: 'delayed hypersensitivity', zh: '遲發型過敏', en: 'Type IV (delayed-type) hypersensitivity', level: 3, aliases: ['第 IV 型過敏', '遲發型（第 IV 型）過敏'], def: '由 T 細胞而非抗體媒介的過敏反應，通常在用藥後數天到數週才出現，不同於吃下去幾分鐘內發作的立即型過敏。' },
  { key: 'sensitivity specificity', zh: '敏感度與特異度', en: 'Sensitivity / specificity', level: 3, aliases: ['敏感度', '特異度'], def: '敏感度是「有病的人被檢出來」的比例；特異度是「沒病的人被正確排除」的比例。兩者都不受疾病有多罕見影響。' },
  { key: 'PPV', zh: '陽性預測值', en: 'Positive predictive value (PPV)', level: 3, def: '檢測陽性的人之中，真的會發病的比例。疾病越罕見，PPV 就越低，這是 HLA 篩檢「陽性者多半不會發病」的原因；但若無法事先分辨誰會發病，仍可能建議陽性者避開該藥。' },
  { key: 'NPV', zh: '陰性預測值', en: 'Negative predictive value (NPV)', level: 3, def: '檢測陰性的人之中，確實不會發病的比例。漢人資料中 HLA-B*15:02 對 carbamazepine 引起 SJS/TEN 的 NPV 接近 100%，但只限該藥該反應，也不是絕對。' },
  { key: 'carrier frequency', zh: '攜帶者比例', en: 'Carrier frequency', level: 3, aliases: ['攜帶者比例', '攜帶者頻率', 'carrier'], def: '族群中至少帶有一個某等位基因的人所占的比例，不同於「等位基因頻率」（所有染色體中該等位基因的占比）。頻率低時前者約為後者的兩倍（哈迪-溫伯格平衡下為 1 − (1 − p)²），比較文獻時不可混用。' },
  { key: 'historical control', zh: '歷史對照', en: 'Historical control', level: 3, def: '用過去估計的發生率當作比較對象，而不是同時期另設對照組。證據強度低於隨機對照試驗。' },
  { key: 'DRESS', zh: '藥物疹合併嗜伊紅血球增多及全身症狀', en: 'Drug reaction with eosinophilia and systemic symptoms', level: 3, def: '延遲數週才出現的嚴重藥物過敏，特徵為發燒、皮疹、嗜伊紅血球增多與器官受累。' },
  { key: 'allopurinol', zh: '別嘌呤醇', en: 'Allopurinol', level: 3, def: '常用來降低血中尿酸、治療痛風的藥物。帶有 HLA-B*58:01 的人使用它，發生嚴重皮膚不良反應（SCAR）的風險大幅上升；台灣自 2022 年 6 月起，健保給付新使用前的 HLA-B*58:01 檢測（需符合特定條件）。' },
  { key: 'abacavir', zh: 'Abacavir', en: 'Abacavir', level: 3, def: '用於 HIV 感染的抗病毒藥物。帶有 HLA-B*57:01 的人可能發生全身性過敏反應，CPIC 指引與 FDA 仿單都建議使用前先檢測、陽性者不使用。' },
  { key: 'NUDT15', zh: 'NUDT15', en: 'Nudix hydrolase 15', level: 3, aliases: ['nudt15'], def: '把具細胞毒性的硫鳥嘌呤代謝物水解成無毒形式的酵素基因。功能降低的變異（如 R139C，屬 *3）在東亞遠比歐洲常見，會讓硫嘌呤類藥物（azathioprine、mercaptopurine）更容易造成骨髓抑制。' },
  { key: 'TPMT', zh: 'TPMT', en: 'Thiopurine S-methyltransferase', level: 3, def: '以甲基化方式代謝硫嘌呤類藥物（azathioprine、mercaptopurine）的酵素基因。活性低的人使用標準劑量容易骨髓抑制；在東亞人，NUDT15 的貢獻通常更大，但 TPMT 並非可以忽略。' },
  { key: 'DPYD', zh: '二氫嘧啶脫氫酶', en: 'Dihydropyrimidine dehydrogenase (DPD)', level: 3, aliases: ['DPD'], def: 'DPYD 基因編碼的酵素，負責分解氟尿嘧啶類藥物（fluorouracil、capecitabine）。活性不足時藥物蓄積，可造成嚴重甚至致命的毒性，所以 FDA 對 capecitabine（Xeloda）的仿單建議開始治療前檢測 DPYD 變異（除非需立即治療）。' },
  { key: 'UGT1A1', zh: 'UGT1A1', en: 'UDP-glucuronosyltransferase 1A1', level: 3, def: '負責把某些藥物（如 irinotecan 的活性代謝物 SN-38）接上葡萄糖醛酸、使其排出的酵素基因。活性較低的變異（如 *28、*6）會讓毒性代謝物留得比較久，增加嚴重嗜中性球低下的風險；*6 在東亞人較常見。' },
  { key: 'TPMI', zh: '台灣精準醫療計畫', en: 'Taiwan Precision Medicine Initiative (TPMI)', level: 3, def: '中央研究院與全台 16 家醫學中心合作的大型研究，依 2025 年 Nature 論文已有 565,390 位參與者同意提供 DNA 並開放電子病歷供研究使用，基因型分析採用針對漢人設計的 SNP 陣列。可用來評估藥物基因變異在真實世界的影響。' },
  { key: 'p-i concept', zh: 'p-i 概念', en: 'Pharmacological interaction with immune receptors (p-i)', level: 4, aliases: ['p-i', 'p-i 模型'], def: '認為藥物不需要共價修飾蛋白質，而是直接以非共價方式結合 HLA 或 TCR，就能活化 T 細胞的模型。' },
  { key: 'altered peptide repertoire', zh: '改變的胜肽庫', en: 'Altered peptide repertoire', level: 4, aliases: ['改變胜肽庫'], def: '藥物結合 HLA 後改變抗原結合溝的形狀，使 HLA 改而呈現原本不呈現的「自己的」胜肽，被 T 細胞當成陌生的東西。' },
  { key: 'hapten', zh: '半抗原', en: 'Hapten / pro-hapten', level: 4, def: '藥物或其反應性代謝物與蛋白質共價結合，形成新抗原的機制（例如盤尼西林類）。' },
]
