// ch10 術語：腫瘤、多基因與 AI
export default [
  { key: 'GWAS', zh: '全基因體關聯分析', en: 'Genome-wide association study', level: 3, aliases: ['GWAS', '曼哈頓圖'], def: '掃描全基因體上數十萬到數百萬個變異，比較有無某性狀（或某種藥物反應）的人，找出統計上相關的位點。結果常畫成「曼哈頓圖」。' },
  { key: 'germline', zh: '生殖細胞變異', en: 'Germline variant', level: 1, aliases: ['生殖細胞', 'germline variant', '種系變異'], def: '遺傳自父母、存在於身體幾乎每個細胞的基因變異，可以傳給下一代。CYP2D6、HLA-B 等傳統藥物基因多半屬於這一類。' },
  { key: 'somatic', zh: '體細胞突變', en: 'Somatic variant', level: 1, aliases: ['體細胞變異', 'somatic variant', 'somatic mutation'], def: '出生後才在部分細胞（例如腫瘤細胞）發生的基因變異，只存在於那群細胞，不會傳給子女。' },
  { key: 'EGFR', zh: '表皮生長因子受體', en: 'Epidermal growth factor receptor', level: 3, aliases: ['EGFR 受體'], def: '嵌在細胞膜上的受體，細胞內側的激酶區接收到生長訊號後會啟動增殖。某些肺腺癌的 EGFR 帶有活化突變，訊號被卡在「開」。' },
  { key: 'kinase', zh: '激酶', en: 'Kinase', level: 3, aliases: ['酪胺酸激酶', 'tyrosine kinase'], def: '一類把 ATP 上的磷酸接到其他蛋白質上的酵素，常被當成細胞內的「開關」；EGFR、ALK 都是酪胺酸激酶。' },
  { key: 'driver-mutation', zh: '驅動突變', en: 'Driver mutation', level: 3, aliases: ['driver mutation'], def: '能推動癌細胞生長與存活的突變。找出驅動突變，常能對應到專門針對它的標靶藥。' },
  { key: 'TKI', zh: '酪胺酸激酶抑制劑', en: 'Tyrosine kinase inhibitor', level: 3, aliases: ['EGFR-TKI', '標靶藥', '標靶治療'], def: '阻斷酪胺酸激酶活性的小分子藥物，常見作法是占住 ATP 口袋。例如 gefitinib、osimertinib、crizotinib。' },
  { key: 'T790M', zh: 'T790M 抗藥突變', en: 'T790M', level: 4, aliases: ['T790M'], def: 'EGFR 激酶區的第二個突變（守門員位置），常在第一代 EGFR 標靶藥使用一段時間後出現；主要機轉是提高激酶對 ATP 的親和力，使與 ATP 競爭的藥物效力下降，是後天抗藥性的原因之一。' },
  { key: 'acquired-resistance', zh: '後天抗藥性', en: 'Acquired resistance', level: 3, aliases: ['acquired resistance'], def: '原本有效的藥物因腫瘤演化出新突變而逐漸失效。因此腫瘤的基因檢測不一定是「一次就好」。' },
  { key: 'trial-enrichment', zh: '試驗富集', en: 'Trial enrichment', level: 4, aliases: ['trial enrichment'], def: '只收有特定生物標記的受試者做臨床試驗，更容易看出真實效果，也避免讓不會受益的人白吃藥。' },
  { key: 'meta-analysis', zh: '統合分析', en: 'Meta-analysis', level: 3, aliases: ['meta-analysis', '統合分析（meta-analysis）'], def: '把多項研究的資料合併起來重新分析，以獲得更大的樣本和更穩定的結論。' },
  { key: 'heritability', zh: '遺傳度', en: 'Heritability', level: 4, aliases: ['heritability'], def: '族群中某性狀的差異有多少比例可歸因於基因差異。高遺傳度不代表用一個基因就能預測個人。' },
  { key: 'standard-error', zh: '標準誤', en: 'Standard error', level: 3, aliases: ['standard error'], def: '估計值的不確定程度。標準誤越大，代表這個估計越不精確，換一批人可能會得到差很多的數字。' },
  { key: 'polygenic', zh: '多基因', en: 'Polygenic', level: 3, aliases: ['多基因性狀', 'polygenic trait'], def: '一個性狀由許多基因、每個只貢獻微小效應共同決定，而不是由單一基因說了算。' },
  { key: 'missing-heritability', zh: '缺失的遺傳度', en: 'Missing heritability', level: 4, aliases: ['missing heritability'], def: '遺傳度估計得很高，但已找到的變異只能解釋其中一小部分的落差。' },
  { key: 'PRS', zh: '多基因風險分數', en: 'Polygenic risk score', level: 4, aliases: ['PRS', 'polygenic risk score'], def: '把許多微小效應的變異加權加總成一個分數，估計某性狀或藥物反應的傾向。用於藥物反應的版本尚未準備好進入常規臨床。' },
  { key: 'VUS', zh: '意義未明變異', en: 'Variant of uncertain significance', level: 4, aliases: ['VUS'], def: '已被偵測到，但目前證據還不足以判斷其功能或臨床意義的變異。' },
  { key: 'MAVE', zh: '多重功能分析', en: 'Multiplexed assay of variant effect', level: 4, aliases: ['MAVE', 'deep mutational scanning', '深度突變掃描', 'VAMP-seq'], def: '一次量測數千個變異功能（如蛋白質豐度或酵素活性）的實驗，用來解讀意義未明的變異。' },
  { key: 'variant-predictor', zh: '變異效應預測器', en: 'Variant effect predictor', level: 4, aliases: ['AlphaMissense'], def: '用序列、演化與結構資訊預測錯義變異可能有害程度的電腦模型。預測的是通用致病性，不等於特定藥物的代謝功能。' },
  { key: 'ancestry-bias', zh: '祖先偏誤', en: 'Ancestry bias', level: 4, aliases: ['ancestry bias', '族群偏誤'], def: '研究資料以某些族群（多為歐洲血統）為主，使結論與預測模型在其他族群的準確度較低。' },
  { key: 'biobank', zh: '生物資料庫', en: 'Biobank', level: 3, aliases: ['biobank'], def: '收集大量參與者的檢體、基因與健康資料供研究使用的資源，例如台灣人體生物資料庫、UK Biobank、All of Us。' },
  { key: 'long-read', zh: '長讀長定序', en: 'Long-read sequencing', level: 4, aliases: ['long-read sequencing'], def: '一次讀取數千到數萬個鹼基的定序技術，較能完整解讀重複序列、假基因與結構變異。' },
  { key: 'gene-editing', zh: '基因編輯', en: 'Genome editing (CRISPR-Cas9)', level: 4, aliases: ['CRISPR', 'CRISPR-Cas9'], def: '用可程式化的核酸酶在指定位置切割並改寫 DNA。它是直接編輯病人自己的基因體，和「依基因型選藥」是不同層次的精準醫療。' },
]
